### ISSUE TITLE
run_atacorrect with error ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by HeChao7021** [loosolab/TOBIAS#101]
When I using ATACorrect , comes the error as following: 
# TOBIAS 0.12.12 ATACorrect (run started 2021-11-20 20:56:15.650358)
# Working directory: /public/home/chaohe/ATAC/final
# Command line call: TOBIAS ATACorrect --bam ../align/V26N0_rep0.bam --genome /public/home/chaohe/db/IWGSC_v1.fasta --peaks V26N0.peaks0.01.bed --outdir ATACorrect_test --cores 8

# ----- Input parameters -----
# bam:	../align/V26N0_rep0.bam
# genome:	/public/home/chaohe/db/IWGSC_v1.fasta
# peaks:	V26N0.peaks0.01.bed
# regions_in:	None
# regions_out:	None
# blacklist:	None
# extend:	100
# split_strands:	False
# norm_off:	False
# track_off:	[]
# k_flank:	12
# read_shift:	[4, -5]
# bg_shift:	100
# window:	100
# score_mat:	DWM
# prefix:	V26N0_rep0
# outdir:	/public/home/chaohe/ATAC/final/ATACorrect_test
# cores:	8
# split:	100
# verbosity:	3

# ----- Output files -----
# /public/home/chaohe/ATAC/final/ATACorrect_test/V26N0_rep0_uncorrected.bw
# /public/home/chaohe/ATAC/final/ATACorrect_test/V26N0_rep0_bias.bw
# /public/home/chaohe/ATAC/final/ATACorrect_test/V26N0_rep0_expected.bw
# /public/home/chaohe/ATAC/final/ATACorrect_test/V26N0_rep0_corrected.bw
# /public/home/chaohe/ATAC/final/ATACorrect_test/V26N0_rep0_atacorrect.pdf

2021-11-20 20:56:15 (29176) [INFO]	----- Processing input data -----
2021-11-20 20:56:15 (29176) [INFO]	Reading info from .bam file
2021-11-20 20:56:15 (29176) [INFO]	Reading info from .fasta file
2021-11-20 20:56:15 (29176) [WARNING]	The following contigs in --bam did not have sequences in --fasta: {'chr6A', 'chr4A', 'chr7B', 'chr7A', 'chr1A', 'chr6D', 'chr3B', 'chrUn', 'chr4B', 'chr5D', 'chr3A', 'chr1D', 'chr2B', 'chr2D', 'chr1B', 'chr3D', 'chr5A', 'chr5B', 'chr4D', 'chr6B', 'chr2A', 'chr7D'}. NOTE: These contigs will be skipped in calculation and output.
2021-11-20 20:56:15 (29176) [INFO]	Processing input/output regions
Traceback (most recent call last):
  File "/public/home/chaohe/miniconda3/envs/py36/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.12.12', 'console_scripts', 'TOBIAS')())
  File "/public/home/chaohe/miniconda3/envs/py36/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/public/home/chaohe/miniconda3/envs/py36/lib/python3.7/site-packages/tobias/tools/atacorrect.py", line 237, in run_atacorrect
    logger.stats("{0}: {1} regions | {2} bp | {3:.2f}% coverage".format(key, len(regions_dict[key]), total_bp, total_bp/genome_bp*100))
ZeroDivisionError: division by zero

The chromosome names  in the bed, bam and genome.fasta file are the same. Could you please help me to fix it? Thank you very much!

**Comment by HeChao7021** [comment]
The reason was found. It's because the chromosome name in fa.fai file  without "chr".
