### ISSUE TITLE
PlotChanges: KeyError(f"None of [{key}] are in the [{axis_name}]")

### ISSUE THREAD

**Issue by zhezhenwang** [loosolab/TOBIAS#110]
Hi, thanks for this powerful tool!

I was trying to use the function PlotChanges and get the following error message:
`PlotChanges --bindetect ~/Downloads/tgf-b3_jasper/bindetect_results.txt --TFS TF_names.txt`
2021-12-22 19:48:55 (66751) [INFO]	Reading data from bindetect file
2021-12-22 19:48:55 (66751) [INFO]	838 TFS found in bindetect file
2021-12-22 19:48:55 (66751) [INFO]	TFS given in --TFS: ['MA0832.1.Tcf21_0832.1', 'PKNOX2', 'MEOX1', 'SNAI1', 'Runx1']
2021-12-22 19:48:55 (66751) [INFO]	Matching given TFs with bindetect file...
2021-12-22 19:48:55 (66751) [INFO]	- MA0832.1.Tcf21_0832.1 matched with: ['MA0832.1.Tcf21_0832.1']
2021-12-22 19:48:55 (66751) [INFO]	- PKNOX2 matched with: ['MA0783.1.PKNOX2_0783.1']
2021-12-22 19:48:55 (66751) [INFO]	- MEOX1 matched with: ['MA0661.1.MEOX1_0661.1']
2021-12-22 19:48:55 (66751) [INFO]	- SNAI1 matched with: ['MA1558.1.SNAI1_1558.1']
2021-12-22 19:48:55 (66751) [INFO]	- Runx1 matched with: ['MA0002.2.Runx1_0002.2']
2021-12-22 19:48:55 (66751) [INFO]	Chosen TFS to view in plot: ['MA0661.1.MEOX1_0661.1', 'MA1558.1.SNAI1_1558.1', 'MA0832.1.Tcf21_0832.1', 'MA0783.1.PKNOX2_0783.1', 'MA0002.2.Runx1_0002.2']
2021-12-22 19:48:55 (66751) [INFO]	Conditions in order: ['vehicle', 'Tgfb']
2021-12-22 19:48:55 (66751) [INFO]	Plotting figure
Traceback (most recent call last):
  File "/Users/zhezhenwang/opt/miniconda3/envs/TOBIAS_ENV/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.13.1', 'console_scripts', 'TOBIAS')())
  File "/Users/zhezhenwang/opt/miniconda3/envs/TOBIAS_ENV/lib/python3.7/site-packages/tobias-0.13.1-py3.7-macosx-10.9-x86_64.egg/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/Users/zhezhenwang/opt/miniconda3/envs/TOBIAS_ENV/lib/python3.7/site-packages/tobias-0.13.1-py3.7-macosx-10.9-x86_64.egg/tobias/tools/plot_changes.py", line 96, in run_plotchanges
    table = bindetect.loc[chosen_TFS]
  File "/Users/zhezhenwang/opt/miniconda3/envs/TOBIAS_ENV/lib/python3.7/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/Users/zhezhenwang/opt/miniconda3/envs/TOBIAS_ENV/lib/python3.7/site-packages/pandas/core/indexing.py", line 1153, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/Users/zhezhenwang/opt/miniconda3/envs/TOBIAS_ENV/lib/python3.7/site-packages/pandas/core/indexing.py", line 1093, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/Users/zhezhenwang/opt/miniconda3/envs/TOBIAS_ENV/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/Users/zhezhenwang/opt/miniconda3/envs/TOBIAS_ENV/lib/python3.7/site-packages/pandas/core/indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['MA0661.1.MEOX1_0661.1', 'MA1558.1.SNAI1_1558.1',\n       'MA0832.1.Tcf21_0832.1', 'MA0783.1.PKNOX2_0783.1',\n       'MA0002.2.Runx1_0002.2'],\n      dtype='object', name='output_prefix')] are in the [index]"

I did notice that 'MA0783.1.PKNOX2_0783.1' does not match with any of the names in bindetect_results.txt, but not sure if this matters
`head bindetect_results.txt`
output_prefix	name	motif_id	cluster	total_tfbs	vehicle_mean_score	vehicle_boundTgfb_mean_score	Tgfb_bound	vehicle_Tgfb_change	vehicle_Tgfb_pvalue
MA0004.1.Arnt_MA0004.1	MA0004.1.Arnt	MA0004.1	C_MA0825.1.MNT	1102	2.99942	145	3.07607	155	-0.00018	4.31940E-01
MA0006.1.AhrArnt_MA0006.1	MA0006.1.Ahr::Arnt	MA0006.1	C_MA0006.1.Ahr::Arnt	1534	2.80555	222	2.80603	188	-0.0044	1.28076E-04
MA0019.1.Ddit3Cebpa_MA0019.1	MA0019.1.Ddit3::Cebpa	MA0019.1	C_MA0019.1.Ddit3::Cebpa	1033	2.58681	114	2.55385	99	0.02023	5.16516E-07

**Comment by msbentsen** [comment]
Hi @zhezhenwang,
Thank you for this report - it looks like some bug in the tool! But I couldn't immediately find the reason for it... the matches are created from the input file, so I don't get how `MA0783.1.PKNOX2_0783.1` cannot match any rows in the file. To debug, would it be possible for you to share the full `bindetect_results.txt` file with me? Either here or per email would be really helpful. Thank you!

**Comment by zhezhenwang** [comment]
[bindetect_results.txt](https://github.com/loosolab/TOBIAS/files/7799522/bindetect_results.txt)
Here it is

**Comment by msbentsen** [comment]
Thank you so much for the file, it was really helpful! It was indeed a bug within the matching of TF names -> names from the input file. I have pushed a fix to the development branch here on Github.

I like to collect a few fixes before I release an official  version, but in the meantime, you can already install the dev version with:
`pip install git+git://github.com/loosolab/TOBIAS@dev`

The output of `TOBIAS --version` should then read `0.13.3-b`. Hope this version helps you out :-)

**Comment by zhezhenwang** [comment]
that sounds perfect, thanks!
