### ISSUE TITLE
matplotlib fails on the final plot

### ISSUE THREAD

**Issue by houghtos** [loosolab/TOBIAS#116]
So I've been running TOBIAS fairly smoothly using JASPAR2022 Core non-redundant, however, whenever I get to the final plot: 

```
2022-02-07 05:56:08 (8448) [INFO]       Progress 99.9%
2022-02-07 05:56:11 (8448) [INFO]       Progress 99.95%
2022-02-07 05:56:12 (8448) [INFO]       Progress 100.0%
2022-02-07 05:56:12 (8448) [INFO]       Progress done!
2022-02-07 05:56:12 (8448) [INFO]       Concatenating results from subsets

2022-02-07 05:56:20 (8448) [INFO]       Writing all_bindetect files
2022-02-07 05:56:21 (8448) [INFO]       Creating BINDetect plot(s)
2022-02-07 05:56:21 (8448) [INFO]       -  KO / WT (static plot)
```

It all kinda goes haywire and fails to build the final dendrogram/volcano plot PDF:

```
2022-02-07 05:56:21 (8448) [INFO]       Creating BINDetect plot(s)
2022-02-07 05:56:21 (8448) [INFO]       - KO / WT (static plot)
Traceback (most recent call last):
  File "~/anaconda3/envs/tobias/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.13.2', 'console_scripts', 'TOBIAS')())
  File "~/anaconda3/envs/tobias/lib/python3.9/site-packages/tobias-0.13.2-py3.9-linux-x86_64.egg/tobias/TOBIAS.py", line 154, in main
    args.func(args)
  File "~/anaconda3/envs/tobias/lib/python3.9/site-packages/tobias-0.13.2-py3.9-linux-x86_64.egg/tobias/tools/bindetect.py", line 810, in run_bindetect
    fig = plot_bindetect(motif_list, clustering, [cond1, cond2], args)
  File "~/anaconda3/envs/tobias/lib/python3.9/site-packages/tobias-0.13.2-py3.9-linux-x86_64.egg/tobias/tools/bindetect_functions.py", line 768, in plot_bindetect
    adjust_text(txts, ax=ax1, add_objects=[l], text_from_points=True, arrowprops=dict(arrowstyle='-', color='black', lw=0.5))  #, expand_text=(0.1,1.2), expand_objects=(0.1,0.1))
  File "~/anaconda3/envs/tobias/lib/python3.9/site-packages/adjustText-0.8b2-py3.9.egg/adjustText/__init__.py", line 730, in adjust_text
    ax.annotate(
  File "~/anaconda3/envs/tobias/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 666, in annotate
    a = mtext.Annotation(text, xy, *args, **kwargs)
  File "~/anaconda3/envs/tobias/lib/python3.9/site-packages/matplotlib/text.py", line 1825, in __init__
    Text.__init__(self, x, y, text, **kwargs)
  File "~/anaconda3/envs/tobias/lib/python3.9/site-packages/matplotlib/text.py", line 160, in __init__
    self.update(kwargs)
  File "~/anaconda3/envs/tobias/lib/python3.9/site-packages/matplotlib/text.py", line 172, in update
    super().update(kwargs)
  File "~/anaconda3/envs/tobias/lib/python3.9/site-packages/matplotlib/artist.py", line 1064, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'Annotation' object has no property 'text_from_points'
```
I'm running this on a Windows 10 linux subsystem conda environment which may be part of the issue? I've gone through and made sure all the packages were installed and while the PDFs, pngs, and all other results have all appeared to have no issues, the 'bindetect_figures.pdf' just fails to be produced. 

I'm hoping to fix this since I'm hoping to run quite a few of these analysis for different data sets and TFBS databases on this machine (and have to focus on other projects concurrently) and thus it would be difficult to write my own script to plot the results at the moment (I also like TOBIAS' output!) 

Any thoughts would be greatly appreciated, I'm currently at a loss after troubleshooting over the weekend.

Edit: Realized I made a mistake in the ATACcorrect step only using consensus peaks from biological replicates and the combined annotated set across conditions during BINDetect. Doing some package updates that may hopefully help and will re-run!

Edit2: Re-ran using corrected combined peaks, updated packages, and attempted to install any possible missing dependencies. Still run into the same error.

**Comment by houghtos** [comment]
Thanks @msbentsen ! Downgrading worked and everything ran to completion!
