### ISSUE TITLE
PlotTracks issue with ImageMagick installation

### ISSUE THREAD

**Issue by imran-aifi** [loosolab/TOBIAS#120]
Hi, 
I am running TOBIAS with the provided test data and examples in the wiki, but when running PlotTracks I have run into the following error in either my wand installation or ImageMagick. I've reinstalled wand (0.6.7) and installed ImageMagick [from source](https://imagemagick.org/script/install-source.php) (I am on Linux) with those checks passing. 
However I still see this error after checking my environment for those packages. 
Thank you for this very useful analysis package, any help or insight into this error is appreciated!

```
# TOBIAS 0.13.2 PlotTracks (run started 2022-02-15 23:17:38.765993)
# Working directory: /home/jupyter
# Command line call: TOBIAS PlotTracks --bigwigs test_data/Bcell_corrected.bw test_data/Tcell_corrected.bw --bigwigs test_data/Bcell_footprints.bw test_data/Tcell_footprints.bw --regions test_data/plot_regions.bed --sites test_data/binding_sites.bed --highlight test_data/binding_sites.bed --gtf test_data/genes.gtf --colors red darkblue red darkblue

# ----- Input parameters -----
# bigwigs:      [['test_data/Bcell_corrected.bw', 'test_data/Tcell_corrected.bw'], ['test_data/Bcell_footprints.bw', 'test_data/Tcell_footprints.bw']]
# regions:      test_data/plot_regions.bed
# sites:        test_data/binding_sites.bed
# highlight:    test_data/binding_sites.bed
# gtf:  test_data/genes.gtf
# width:        15
# colors:       ['red', 'darkblue', 'red', 'darkblue']
# labels:       None
# max_transcripts:      1
# outdir:       plottracks_output
# verbosity:    3


2022-02-15 23:17:38 (32323) [INFO]      Plotting region: ['chr4', '119628321', '119629356']
sh: 1: gs: not found
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/svist4get/methods.py", line 37, in pdf_page_to_png
    page = Image(filename=filename, resolution=resolution)
  File "/opt/conda/lib/python3.7/site-packages/wand/image.py", line 9144, in __init__
    self.read(filename=filename)
  File "/opt/conda/lib/python3.7/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/opt/conda/lib/python3.7/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.DelegateError: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r600x600' -dPrinted=false  '-sOutputFile=/tmp/magick-ARm3l0Ejdzqf_6aWnaBAb_p0Un6LnWsi%d' '-f/tmp/magick-cQIUrQPyHFCARobMYd1_9WDu7gEu3Glh' '-f/tmp/magick-W-hx75ST7RYY29Rje3Ogl4XAFBOihtZh'' (32512) @ error/ghostscript-private.h/ExecuteGhostscriptCommand/74

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/TOBIAS", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)
  File "/opt/conda/lib/python3.7/site-packages/tobias/tools/plot_tracks.py", line 372, in run_tracks
    sv4g.methods.pdf_page_to_png(pa)    #pdf to png
  File "/opt/conda/lib/python3.7/site-packages/svist4get/methods.py", line 58, in pdf_page_to_png
    raise Svist4getError('Unable to convert the pdf file to png. There might be a problem with the \'wand\' python package or with ImageMagick installation.') from error
svist4get.methods.Svist4getError: Unable to convert the pdf file to png. There might be a problem with the 'wand' python package or with ImageMagick installation.
```

**Comment by msbentsen** [comment]
Hi,

I haven't seen that error before, but I think it is actually arising due to: 
```sh: 1: gs: not found```

A bit of googling tells me that it might be due to `Ghost Script` not being installed on your system, or not being available on the path. Could this be the case? Please let me know, and then I might be able to build in a better check into the tool, thanks!

**Comment by msbentsen** [comment]
Great, thank you for confirming @imran-aifi! I included a small check in PlotTracks, so that will be available in a future version. Let me know if you encounter any more issues.
