### ISSUE TITLE
Question about CreateNetwork

### ISSUE THREAD

**Issue by HuaxingHuang** [loosolab/TOBIAS#135]
While I am trying step by step to process my ATAC Seq data, I am stuck in the step of CreateNetwork. I am running TOBIAS CreateNetwork with all the TFBS in one run. The command is : TOBIAS CreateNetwork --TFBS */beds/*_SE_bound.bed --origin ./motif2gene_mapping.txt. The motif2gene_mapping.txt file is copied from the data file you provided.  The format of the bound.bed file is as follows:

chr1    781274  781288  GABPA_MA0062.3  8.68256 +       chr1    780822  781682  peak_270        .       .       ENSG00000225880 LINC00115       0.29491
chr1    848356  848370  GABPA_MA0062.3  7.8939  -       chr1    845864  849734  peak_397        .       .       ENSG00000187634 SAMD11  0.22441

The ERROR report is as follows:

2022-05-07 13:50:18 (214606) [WARNING]	Subset 25813950 sites to 0 sites with a valid source id in the '--origin' table
2022-05-07 13:50:18 (214606) [INFO]	Subset 0 sites to 0 sites with any target given
2022-05-07 13:50:18 (214606) [INFO]	Subset 0 sites to 0 sites with matching target id in '--origin'
Traceback (most recent call last):
  File "/data/Conda3/envs/TOBIAS/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.12.6', 'console_scripts', 'TOBIAS')())
  File "/data/Conda2/envs/TOBIAS/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/data/Conda2/envs/TOBIAS/lib/python3.7/site-packages/tobias/tools/create_network.py", line 163, in run_network
    sites_table_convert = sites_table.merge(origin_table[[source_col_origin, target_col_origin]], left_on=target_col_tfbs, right_on=target_col_origin, how="inner")
  File "/data/Conda2/envs/TOBIAS/lib/python3.7/site-packages/pandas/core/frame.py", line 8205, in merge
    validate=validate,
  File "/data/Conda2/envs/TOBIAS/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 87, in merge
    validate=validate,
  File "/data/Conda2/envs/TOBIAS/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 668, in __init__
    ) = self._get_merge_keys()
  File "/data/Conda2/envs/TOBIAS/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1033, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/data/Conda2/envs/TOBIAS/lib/python3.7/site-packages/pandas/core/generic.py", line 1697, in _get_label_or_level_values
    f"The {label_axis_name} label '{key}' is not unique.{multi_message}"
ValueError: The column label 'Origin_0' is not unique.

I was hoping that you could maybe help me out. Any help would be immensely appreciated!

all the best,
Huaxing Huang

**Comment by msbentsen** [comment]
Hi, thank you for your issue. I realize this module is not so well documented, sorry about that! It should really break off after the first warning of subsetting the number of sites to 0, as this obviously breaks the analysis.

It looks like there might not be a good fit between the names in `motif2gene_mapping.txt` file and the 4th column of the input --TFBS. Can you check if this is the case? Otherwise, would it be possible for you to run the tool with `--verbosity 4` and post the full log here? This will make `CreateNetwork` write some debugging log messages, which might tell what is wrong.

**Comment by HuaxingHuang** [comment]
您的邮件我已收到，谢谢，我会尽快回复的！
