### ISSUE TITLE
Trouble using ClusterMotifs

### ISSUE THREAD

**Issue by is438indu** [loosolab/TOBIAS#162]
Dear TOBIAS developers,

Thank you for creating TOBIAS.  I am having trouble using ClusterMotifs module. 
I get the following error msg when I tried using ClusterMotifs:

Cmd used :ClusterMotifs --dist_method wic --motifs ERF2_34_nozeros.meme
(I replaced all zeros in the matrix file with 10-6. Default method pcc did not work since gimmemotifs installed is 0.17.0. gimmemotifs was installed with pip)
----- Input parameters -----
motifs:	['ERF2_34_nozeros.meme']
threshold:	0.3
dist_method:	wic
clust_method:	average
cons_format:	jaspar
prefix:	motif_comparison
outdir:	clustermotifs_output
verbosity:	3
type:	pdf
dpi:	100
color:	YlOrRd_r

2022-09-22 16:41:35 (26421) [INFO]	Reading input file(s)
2022-09-22 16:41:35 (26421) [STATS]	- Read 34 motifs from ERF2_34_nozeros.meme (format: meme)
2022-09-22 16:41:35 (26421) [INFO]	Creating matrix statistics
2022-09-22 16:41:35 (26421) [INFO]	Clustering motifs
Traceback (most recent call last):
  File "/Users/is438/miniconda3/envs/py3pt7/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.13.3', 'console_scripts', 'TOBIAS')())
  File "/Users/is438/miniconda3/envs/py3pt7/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/Users/is438/miniconda3/envs/py3pt7/lib/python3.7/site-packages/tobias/tools/motif_clust.py", line 347, in run_motifclust
    clusters = motif_list.cluster(threshold=args.threshold, metric=args.dist_method, clust_method=args.clust_method)
  File "/Users/is438/miniconda3/envs/py3pt7/lib/python3.7/site-packages/tobias/utils/motifs.py", line 511, in cluster
    fclust_labels = fcluster(self.linkage_mat, threshold, criterion="distance")			#cluster membership per motif
  File "/Users/is438/miniconda3/envs/py3pt7/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 2576, in fcluster
    is_valid_linkage(Z, throw=True, name='Z')
  File "/Users/is438/miniconda3/envs/py3pt7/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 2281, in is_valid_linkage
    name_str)
ValueError: Linkage 'Z' contains negative distances.

I also installed TOBIAS and gimme motifs with pip, and tried running ClusterMotifs. It still did not run. 

Please advise.

Thanks
Indu

**Comment by msbentsen** [comment]
Hi Indu,

Thank you for raising this issue - it looks like the "wic" distance method is incompatible with ClusterMotifs due to creating negative distances. I wasn't aware of this, so I will create a check for this in a future version.

Until then, I would recommend you to use `--dist_method seqcor` for the run. Hope this works out for you!

BR Mette

**Comment by is438indu** [comment]
Hi Mette,

Thank you for the response. Run with seqcor works. Thanks :)

Indu
