### ISSUE TITLE
TOBIAS CreateNetwork

### ISSUE THREAD

**Issue by AndressaOL** [loosolab/TOBIAS#164]
Hi, I am trying to use TOBIAS in my ATAC-seq data, and I can't move forward with the create a TF network. I got the error below.
Besides the bed files (*_bound.bed), I created a list using all the genes in the .gff file (NCBI database).  However, I did not see any correspondence gene id with the *_bound.bed.  I also tried to use the two first columns from BINDdetect results the error did not change (I used the JASPAR_core_redundant to predict the TFBS). 
Also, I am trying to understand this function. I would like to build a network that includes the TFs (TFBS) with the potential genes (not TFs) that could interact with these TFBS (from bound.bed), but based on the input file seems this function can only build the interaction between the motifs from bound.bed file.  
I hope you can help me.

2022-09-28 09:58:07 (208199) [INFO]     Reading all input binding sites
Traceback (most recent call last):
  File "/net/hawkins/vol1/home/aolima/miniconda2/envs/TOBIAS_ENV/bin/TOBIAS", line 8, in <module>
    sys.exit(main())
  File "/net/hawkins/vol1/home/aolima/miniconda2/envs/TOBIAS_ENV/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)
  File "/net/hawkins/vol1/home/aolima/miniconda2/envs/TOBIAS_ENV/lib/python3.7/site-packages/tobias/tools/create_network.py", line 85, in run_network
    df = pd.read_csv(fil, sep="\t", header=None)
  File "/net/hawkins/vol1/home/aolima/miniconda2/envs/TOBIAS_ENV/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/net/hawkins/vol1/home/aolima/miniconda2/envs/TOBIAS_ENV/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/net/hawkins/vol1/home/aolima/miniconda2/envs/TOBIAS_ENV/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/net/hawkins/vol1/home/aolima/miniconda2/envs/TOBIAS_ENV/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/net/hawkins/vol1/home/aolima/miniconda2/envs/TOBIAS_ENV/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/net/hawkins/vol1/home/aolima/miniconda2/envs/TOBIAS_ENV/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

My inputs: 
origin:
NCBI
COX2    ENSGALG00010000020
COX3    ENSGALG00010000024
PDIA3   ENSGALG00010000039
CKMT1B  ENSGALG00010000042
TP53BP1 ENSGALG00010000045
IQGAP3  ENSGALG00010000047
FES     ENSGALG00010000049
CIB1    ENSGALG00010000050
FURIN   ENSGALG00010000058
MFAP1   ENSGALG00010000059

-BINDetect results
AGL3_MA0001.1   AGL3
RUNX1_MA0002.1  RUNX1
TFAP2A_MA0003.1 TFAP2A
Arnt_MA0004.1   Arnt
AG_MA0005.1     AG
AhrArnt_MA0006.1        Ahr::Arnt
Ar_MA0007.1     Ar
HAT5_MA0008.1   HAT5
Tbxt_MA0009.1   Tbxt
br_MA0010.1     br
br_MA0011.1     br
br_MA0012.1     br
br_MA0013.1     br

TFBS: 
TOBIAS CreateNetwork --TFBS BINDdetect/*/beds/*_footprints_bound.bed 
NC_052532.1     91392806        91392813        abd-A_MA0206.1  8.19787 -       NC_052532.1     91392628        91392937        control_kidney_final_peak_2118  159     .       4.78209 18.70264        15.94599  131      31.56913
NC_052532.1     108310175       108310182       abd-A_MA0206.1  8.19787 -       NC_052532.1     108310048       108310293       control_kidney_final_peak_2449  228     .       5.21008 25.82904        22.86217  98       34.25362
NC_052532.1     109246550       109246557       abd-A_MA0206.1  8.19787 -       NC_052532.1     109246421       109246625       control_kidney_final_peak_2473  64      .       2.57511 8.73171 6.41977 111     32.35066
NC_052533.1     19196196        19196203        abd-A_MA0206.1  8.98235 +       NC_052533.1     19196091        19196298        control_kidney_final_peak_4658  109     .       3.56601 13.55083        10.99193  130      31.65298
NC_052533.1     122752696       122752703       abd-A_MA0206.1  8.19787 +       NC_052533.1     122752564       122752773       control_kidney_final_peak_6807  106     .       3.96812 13.14694        10.60423  85       28.25735

**Comment by msbentsen** [comment]
Hi, 

Thank you for your question. I think there are two things to consider here:
1. I discovered a bug in CreateNetwork leading to the error above, due one/more of the input files being empty. I included a test for this now (currently on the dev branch but will be released as `tobias 0.14.0` soon). So that should solve it.
2. In order to use CreateNetwork, you must annotate each TFBS with its target gene. I can recommend you to use the snakemake pipeline for TOBIAS, as this automatically does this: https://github.molgen.mpg.de/loosolab/TOBIAS_snakemake. You can also use [UROPA](https://github.com/loosolab/UROPA) (which is what the pipeline uses), directly on the "_bound.bed" files. 

If you only want to get the interaction of TFBS to all genes, you can annotate each site and look directly at the TFBS -> gene assignment. I hope this is helpful!

BR Mette

**Comment by AndressaOL** [comment]
I will see the snakemake pipeline for now. Thanks so much for the reply.
