### ISSUE TITLE
error runnning the TOBIAS ATACorrect 

### ISSUE THREAD

**Issue by archanabhardwaj** [loosolab/TOBIAS#175]
Thanks for this amazing tool.  I am trying to run this software on one of the ATAC file. But it gives error while running the "TOBIAS ATACorrect" step. 

TOBIAS ATACorrect --bam R1_001.bam  --genome genome.fa  --peaks narrowPeak.bed  --prefix test1 

## few lines
2022-12-12 14:34:37 (245564) [INFO]     Progress: 99%
2022-12-12 14:34:37 (245564) [STATS]    TOTAL_READS     0
2022-12-12 14:34:37 (245564) [STATS]    PEAK_READS      0
2022-12-12 14:34:37 (245564) [STATS]    NONPEAK_READS   0
Traceback (most recent call last):
  File "/home/user/.conda/envs/tobias/bin/TOBIAS", line 11, in <module>
    load_entry_point('tobias==0.8.0', 'console_scripts', 'TOBIAS')()
  File "/home/user/.conda/envs/tobias/lib/python3.7/site-packages/tobias/TOBIAS.py", line 152, in main
    args.func(args)             #run specified function with arguments
  File "/home/user/.conda/envs/tobias/lib/python3.7/site-packages/tobias/footprinting/atacorrect.py", line 317, in run_atacorrect
    lib_norm = 10000000/reads_total
ZeroDivisionError: division by zero
Problem in main logger process:
Traceback (most recent call last):
  File "/home/user/.conda/envs/tobias/lib/python3.7/site-packages/tobias/utils/logger.py", line 147, in main_logger_process
    record = self.queue.get()
  File "<string>", line 2, in get
  File "/home/user/.conda/envs/tobias/lib/python3.7/multiprocessing/managers.py", line 819, in _callmethod
    kind, result = conn.recv()
  File "/home/user/.conda/envs/tobias/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/user/.conda/envs/tobias/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/user/.conda/envs/tobias/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

I would appreciate all the suggestion. 
Thanks in advance

**Comment by msbentsen** [comment]
Hi, 

Thank you for your issue. Can you post the full logfile? The last couple of lines before the error shows that no reads were found in the .bam-file:

> 2022-12-12 14:34:37 (245564) [STATS] TOTAL_READS 0
2022-12-12 14:34:37 (245564) [STATS] PEAK_READS 0
2022-12-12 14:34:37 (245564) [STATS] NONPEAK_READS 0

Can you confirm that there are reads in the .bam and that the chromosome names fit those within `genome.fa`?

**Comment by archanabhardwaj** [comment]
Hi 
Thanks for your quick response. Here you can find full runtime details

# TOBIAS 0.13.3 ATACorrect (run started 2022-12-12 15:52:47.185911)
# Working directory: /home/user/Desktop/TOBIAS
# Command line call: TOBIAS ATACorrect --bam R1_001.bam --genome hg38.fa --peaks R1_001.narrowPeak.bed --prefix test1 --cores 1

# ----- Input parameters -----
# bam:	R1_001.bam
# genome:	hg38.fa
# peaks:	R1_001.narrowPeak.bed
# regions_in:	None
# regions_out:	None
# blacklist:	None
# extend:	100
# split_strands:	False
# norm_off:	False
# track_off:	[]
# k_flank:	12
# read_shift:	[4, -5]
# bg_shift:	100
# window:	100
# score_mat:	DWM
# prefix:	test1
# outdir:	/home/user/Desktop/TOBIAS
# cores:	1
# split:	100
# verbosity:	3


# ----- Output files -----
# /home/user/Desktop/test1_uncorrected.bw
# /home/user/Desktop/test1_bias.bw
# /home/user/Desktop/test1_expected.bw
# /home/user/Desktop/test1_corrected.bw
# /home/user/Desktop/test1_atacorrect.pdf


2022-12-12 15:52:47 (103431) [INFO]	----- Processing input data -----
2022-12-12 15:52:47 (103431) [INFO]	Reading info from .bam file
2022-12-12 15:52:47 (103431) [INFO]	Reading info from .fasta file
2022-12-12 15:52:47 (103431) [INFO]	Processing input/output regions
2022-12-12 15:52:55 (103431) [STATS]	genome: 454 regions | 3209269536 bp | 100.00% coverage
2022-12-12 15:52:55 (103431) [STATS]	input_regions: 160675 regions | 3181825444 bp | 99.14% coverage
2022-12-12 15:52:55 (103431) [STATS]	output_regions: 127263 regions | 54001204 bp | 1.68% coverage
2022-12-12 15:52:55 (103431) [STATS]	peak_regions: 134680 regions | 27444092 bp | 0.86% coverage
2022-12-12 15:52:55 (103431) [STATS]	nonpeak_regions: 160675 regions | 3181825444 bp | 99.14% coverage
2022-12-12 15:52:55 (103431) [STATS]	blacklist_regions: 0 regions | 0 bp | 0.00% coverage

2022-12-12 15:52:55 (103431) [INFO]	----- Estimating normalization factors -----
2022-12-12 15:52:55 (103431) [INFO]	Counting reads in peak regions
2022-12-12 15:52:55 (103431) [INFO]	Progress: 0%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 1%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 2%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 3%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 4%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 5%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 6%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 7%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 8%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 9%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 10%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 11%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 12%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 13%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 14%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 15%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 16%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 17%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 18%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 19%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 20%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 21%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 22%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 23%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 24%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 25%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 26%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 27%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 28%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 29%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 30%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 31%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 32%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 33%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 34%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 35%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 36%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 37%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 38%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 39%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 40%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 41%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 42%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 43%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 44%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 45%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 46%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 47%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 48%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 49%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 50%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 51%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 52%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 53%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 54%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 55%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 56%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 57%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 58%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 59%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 60%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 61%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 62%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 63%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 64%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 65%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 66%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 67%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 68%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 69%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 70%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 71%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 72%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 73%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 74%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 75%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 76%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 77%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 78%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 79%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 80%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 81%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 82%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 83%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 84%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 85%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 86%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 87%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 88%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 89%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 90%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 91%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 92%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 93%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 94%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 95%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 96%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 97%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 98%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 99%

2022-12-12 15:52:55 (103431) [INFO]	Counting reads in nonpeak regions
2022-12-12 15:52:55 (103431) [INFO]	Progress: 0%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 1%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 2%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 3%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 4%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 5%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 6%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 7%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 8%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 9%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 10%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 11%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 12%
2022-12-12 15:52:55 (103431) [INFO]	Progress: 13%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 14%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 15%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 16%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 17%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 18%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 19%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 20%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 21%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 22%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 23%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 24%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 25%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 26%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 27%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 28%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 29%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 30%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 31%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 32%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 33%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 34%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 35%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 36%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 37%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 38%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 39%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 40%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 41%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 42%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 43%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 44%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 45%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 46%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 47%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 48%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 49%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 50%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 51%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 52%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 53%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 54%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 55%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 56%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 57%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 58%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 59%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 60%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 61%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 62%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 63%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 64%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 65%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 66%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 67%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 68%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 69%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 70%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 71%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 72%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 73%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 74%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 75%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 76%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 77%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 78%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 79%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 80%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 81%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 82%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 83%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 84%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 85%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 86%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 87%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 88%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 89%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 90%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 91%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 92%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 93%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 94%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 95%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 96%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 97%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 98%
2022-12-12 15:52:56 (103431) [INFO]	Progress: 99%
2022-12-12 15:52:56 (103431) [STATS]	TOTAL_READS	0
2022-12-12 15:52:56 (103431) [STATS]	PEAK_READS	0
2022-12-12 15:52:56 (103431) [STATS]	NONPEAK_READS	0
2022-12-12 15:52:56 (103466) [ERROR]	Multiprocessing logger lost connection to queue - probably due to an error raised from a child process.

I have checked **all bamfile header ; peak chromsomes labels and genome chromosome labels.**  Same genome.fa was used for the peak calling and reference mapping of reads to fa file. 

I am not sure how to proceed further with this error. I would appreciate all your suggestions,

**Comment by msbentsen** [comment]
Can you have a look at the output of `samtools flagstat <yourbam>`? Just to see if the file contains properly mapped reads.

**Comment by archanabhardwaj** [comment]
Problem was in the bam files. With correct bam files, pipeline is running now. Many thanks for your help !!

**Comment by msbentsen** [comment]
That sounds great @archanabhardwaj, thank you for the update! I will close the issue here, but please reopen if there are any other issues.
