### ISSUE TITLE
Motifs p-value threshold error

### ISSUE THREAD

**Issue by JavBurgoa** [loosolab/TOBIAS#18]
HI! I posted an issue yesterday 11/5/2020 that was solved today 12/5/2020. However I encountered a problem while performing the solution.
The original problem was that using my own motifs in JASPAR format I could not get TOBIAS BINDetect to find motifs with 0 mismatches.
The JASPAR Motif format:
```
>AGGTCATGACCG   IR0-1
A [ 100 0 0 0 0 100 0 0 100 0 0 0]
C [ 0 0 100 0 0 0 0 0 0 0 0 100]
T [ 0 100 100 0 0 100 0 100 0 0 0 0]
G [ 100 0 0 100 0 0 0 0  0 100 0]
```
Where bases with a score of 100 belong to the motif and values of 0 don't.
The solution was to simply use `--motifs-pvalue` with a very low number (default being 1x10^-4) to force 0 mismatches. However, if i lower the p-value too much (more than 1x10^-6) it gives an error. Here I post the code i used and the subsequent error:
Code:
```
TOBIAS BINDetect --motifs AllMotifs.jaspar \
                --signals ScoreRA.bw Scorewt.bw \
                --genome ~/Spur_Data/genome.fasta \
                --peaks Peaks.bed \
                --motif-pvalue 0.00001 \
                --peak_header Peak_header.txt \
                --outdir BINDetect_output_trial \
                --cond_names RA wt \
                --cores 16

```
Output message
```
# TOBIAS 0.11.1-dev BINDetect (run started 2020-05-12 14:58:32.063234)
# Working directory: /home/jburgoa/ATAC-seq_differential_RA/Data
# Command line call: TOBIAS BINDetect --motifs /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/JASPAR/AllMotifs.jaspar --signals /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/ScoreBigWig/RA24_ATAC_footprints.bw /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/ScoreBigWig/wt24_ATAC_footprints.bw --genome /home/jburgoa/Spur_Data/GCF_000002235.5_Spur_5.0_genomic.fna --peaks /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/Initial_data/FinalJoined_Windowed_All_merged.bed --motif-pvalue 0.000001 --peak_header /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/Initial_data/Peak_header.txt --outdir /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/24hpf_BINDetect_output_trial --cond_names RA wt --cores 16

# ----- Input parameters -----
# signals:      ['/home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/ScoreBigWig/RA24_ATAC_footprints.bw', '/home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/ScoreBigWig/wt24_ATAC_footprints.bw']
# peaks:        /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/Initial_data/FinalJoined_Windowed_All_merged.bed
# motifs:       ['/home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/JASPAR/AllMotifs.jaspar']
# genome:       /home/jburgoa/Spur_Data/GCF_000002235.5_Spur_5.0_genomic.fna
# cond_names:   ['RA', 'wt']
# peak_header:  /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/Initial_data/Peak_header.txt
# naming:       name_id
# motif_pvalue: 1e-06
# bound_pvalue: 0.001
# pseudo:       None
# time_series:  False
# skip_excel:   False
# prefix:       bindetect
# outdir:       /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/24hpf_BINDetect_output_trial
# cores:        16
# split:        100
# verbosity:    3


# ----- Output files -----
# /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/24hpf_BINDetect_output_trial/*/beds/*_RA_bound.bed
# /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/24hpf_BINDetect_output_trial/*/beds/*_RA_unbound.bed
# /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/24hpf_BINDetect_output_trial/*/beds/*_wt_bound.bed
# /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/24hpf_BINDetect_output_trial/*/beds/*_wt_unbound.bed
# /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/24hpf_BINDetect_output_trial/*/beds/*_all.bed
# /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/24hpf_BINDetect_output_trial/*/plots/*_log2fcs.pdf
# /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/24hpf_BINDetect_output_trial/*/*_overview.txt
# /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/24hpf_BINDetect_output_trial/*/*_overview.xlsx
# /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/24hpf_BINDetect_output_trial/bindetect_distances.txt
# /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/24hpf_BINDetect_output_trial/bindetect_results.txt
# /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/24hpf_BINDetect_output_trial/bindetect_results.xlsx
# /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/BINDetect/24hpf_BINDetect_output_trial/bindetect_figures.pdf


/opt/pyenv/tobias-env/lib/python3.8/site-packages/logomaker-0.8-py3.8.egg/logomaker/src/validate.py:98: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if matrix_type is 'information':
/opt/pyenv/tobias-env/lib/python3.8/site-packages/logomaker-0.8-py3.8.egg/logomaker/src/validate.py:104: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif matrix_type is 'probability':
2020-05-12 14:58:32 (6108) [INFO]       ----- Processing input data -----
2020-05-12 14:58:32 (6108) [INFO]       Checking reading/writing of files
2020-05-12 14:58:32 (6108) [INFO]       Reading peaks
2020-05-12 14:58:33 (6108) [INFO]       - Found 100254 regions in input peaks
2020-05-12 14:58:33 (6108) [INFO]       - Merged to 100254 regions
2020-05-12 14:58:33 (6108) [INFO]       Checking for match between --peaks and --fasta/--signals boundaries
2020-05-12 14:58:33 (6108) [INFO]       - Comparing peaks to /home/jburgoa/Spur_Data/GCF_000002235.5_Spur_5.0_genomic.fna
2020-05-12 14:58:33 (6108) [INFO]       - Comparing peaks to /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/ScoreBigWig/RA24_ATAC_footprints.bw
2020-05-12 14:58:33 (6108) [INFO]       - Comparing peaks to /home/jburgoa/ATAC-seq_differential_RA/Data/TOBIAS/Retinoic_Acid/ScoreBigWig/wt24_ATAC_footprints.bw
2020-05-12 14:58:33 (6108) [INFO]       Estimating GC content from peak sequences
2020-05-12 14:58:34 (6108) [INFO]       - GC content estimated at 43.62%
2020-05-12 14:58:34 (6108) [INFO]       Reading motifs from file
2020-05-12 14:58:35 (6108) [INFO]       - Read 68 motifs
2020-05-12 14:58:35 (6108) [INFO]       Creating folder structure for each TF
2020-05-12 14:58:36 (6108) [INFO]       Plotting sequence logos for each motif
2020-05-12 14:58:36 (6108) [INFO]       Progress 0%
2020-05-12 14:58:37 (6108) [INFO]       Progress 20.6%
2020-05-12 14:58:37 (6108) [INFO]       Progress 22.1%
2020-05-12 14:58:37 (6108) [INFO]       Progress 42.6%
2020-05-12 14:58:37 (6108) [INFO]       Progress 44.1%
2020-05-12 14:58:37 (6108) [INFO]       Progress 64.7%
2020-05-12 14:58:37 (6108) [INFO]       Progress 66.2%
2020-05-12 14:58:37 (6108) [INFO]       Progress 75.0%
2020-05-12 14:58:37 (6108) [INFO]       Progress 86.8%
2020-05-12 14:58:37 (6108) [INFO]       Progress 94.1%
2020-05-12 14:58:38 (6108) [INFO]       Progress 100.0%
2020-05-12 14:58:38 (6108) [INFO]       Progress done!


2020-05-12 14:58:38 (6108) [INFO]       Scanning for motifs and matching to signals...
2020-05-12 14:58:38 (6108) [INFO]       Progress 0%
2020-05-12 14:58:38 (6108) [INFO]       Progress 1.0%
2020-05-12 14:58:39 (6108) [INFO]       Progress 4.0%
2020-05-12 14:58:39 (6108) [INFO]       Progress 6.0%
2020-05-12 14:58:39 (6108) [INFO]       Progress 9.0%
2020-05-12 14:58:39 (6108) [INFO]       Progress 12.0%
2020-05-12 14:58:39 (6108) [INFO]       Progress 15.0%
2020-05-12 14:58:39 (6108) [INFO]       Progress 19.0%
2020-05-12 14:58:39 (6108) [INFO]       Progress 21.0%
2020-05-12 14:58:39 (6108) [INFO]       Progress 22.0%
2020-05-12 14:58:40 (6108) [INFO]       Progress 25.0%
2020-05-12 14:58:40 (6108) [INFO]       Progress 28.0%
2020-05-12 14:58:40 (6108) [INFO]       Progress 29.0%
2020-05-12 14:58:40 (6108) [INFO]       Progress 32.0%
2020-05-12 14:58:40 (6108) [INFO]       Progress 35.0%
2020-05-12 14:58:40 (6108) [INFO]       Progress 37.0%
2020-05-12 14:58:40 (6108) [INFO]       Progress 38.0%
2020-05-12 14:58:40 (6108) [INFO]       Progress 41.0%
2020-05-12 14:58:40 (6108) [INFO]       Progress 43.0%
2020-05-12 14:58:40 (6108) [INFO]       Progress 46.0%
2020-05-12 14:58:41 (6108) [INFO]       Progress 50.0%
2020-05-12 14:58:41 (6108) [INFO]       Progress 52.0%
2020-05-12 14:58:41 (6108) [INFO]       Progress 55.0%
2020-05-12 14:58:41 (6108) [INFO]       Progress 58.0%
2020-05-12 14:58:41 (6108) [INFO]       Progress 61.0%
2020-05-12 14:58:41 (6108) [INFO]       Progress 64.0%
2020-05-12 14:58:41 (6108) [INFO]       Progress 67.0%
2020-05-12 14:58:41 (6108) [INFO]       Progress 70.0%
2020-05-12 14:58:42 (6108) [INFO]       Progress 73.0%
2020-05-12 14:58:42 (6108) [INFO]       Progress 77.0%
2020-05-12 14:58:42 (6108) [INFO]       Progress 79.0%
2020-05-12 14:58:42 (6108) [INFO]       Progress 82.0%
2020-05-12 14:58:42 (6108) [INFO]       Progress 85.0%
2020-05-12 14:58:42 (6108) [INFO]       Progress 87.0%
2020-05-12 14:58:42 (6108) [INFO]       Progress 90.0%
2020-05-12 14:58:42 (6108) [INFO]       Progress 93.0%
2020-05-12 14:58:42 (6108) [INFO]       Progress 95.0%
2020-05-12 14:58:42 (6108) [INFO]       Progress 97.0%
2020-05-12 14:58:43 (6108) [INFO]       Progress 100.0%
2020-05-12 14:58:43 (6108) [INFO]       Progress done!
2020-05-12 14:58:43 (6108) [INFO]       Done scanning for TFBS across regions!
2020-05-12 14:58:43 (6108) [INFO]       Waiting for bedfiles to write
2020-05-12 14:58:43 (6108) [INFO]       Merging results from subsets

2020-05-12 14:58:43 (6108) [INFO]       Estimating score distribution per condition
2020-05-12 14:58:44 (6108) [INFO]       Normalizing scores
2020-05-12 14:58:44 (6108) [INFO]       Estimating bound/unbound threshold
2020-05-12 14:58:46 (6108) [STATS]      - Threshold estimated at: 1.77416

2020-05-12 14:58:46 (6108) [INFO]       Calculating background log2 fold-changes between conditions
2020-05-12 14:58:46 (6108) [INFO]       - RA / wt

2020-05-12 14:58:47 (6108) [INFO]       Processing scanned TFBS individually
2020-05-12 14:58:47 (6108) [INFO]       Progress 0%
2020-05-12 14:58:47 (6108) [INFO]       Progress 1.5%
2020-05-12 14:58:47 (6108) [INFO]       Progress 5.9%
2020-05-12 14:58:47 (6108) [INFO]       Progress 23.5%
2020-05-12 14:58:47 (6108) [INFO]       Progress 35.3%
2020-05-12 14:58:48 (6108) [INFO]       Progress 45.6%
2020-05-12 14:58:48 (6108) [INFO]       Progress 58.8%
2020-05-12 14:58:48 (6108) [INFO]       Progress 67.6%
2020-05-12 14:58:48 (6108) [INFO]       Progress 76.5%
2020-05-12 14:58:48 (6108) [INFO]       Progress 86.8%
2020-05-12 14:58:49 (6108) [INFO]       Progress 89.7%
2020-05-12 14:58:49 (6108) [INFO]       Progress 95.6%
2020-05-12 14:58:49 (6108) [INFO]       Progress 100.0%
2020-05-12 14:58:49 (6108) [INFO]       Progress done!
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/pyenv/tobias-env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'RA_score'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python-3.8.2/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/pyenv/tobias-env/lib/python3.8/site-packages/tobias-0.11.1.dev0-py3.8-linux-x86_64.egg/tobias/tools/bindetect_functions.py", line 370, in process_tfbs
    info_table.at[TF_name, condition + "_mean_score"] = round(np.mean(bed_table[condition + "_score"]), 5)
  File "/opt/pyenv/tobias-env/lib/python3.8/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/pyenv/tobias-env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'RA_score'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pyenv/tobias-env/bin/TOBIAS", line 11, in <module>
    load_entry_point('tobias==0.11.1.dev0', 'console_scripts', 'TOBIAS')()
  File "/opt/pyenv/tobias-env/lib/python3.8/site-packages/tobias-0.11.1.dev0-py3.8-linux-x86_64.egg/tobias/TOBIAS.py", line 154, in main
  File "/opt/pyenv/tobias-env/lib/python3.8/site-packages/tobias-0.11.1.dev0-py3.8-linux-x86_64.egg/tobias/tools/bindetect.py", line 526, in run_bindetect
  File "/opt/pyenv/tobias-env/lib/python3.8/site-packages/tobias-0.11.1.dev0-py3.8-linux-x86_64.egg/tobias/tools/bindetect.py", line 526, in <listcomp>
  File "/opt/python-3.8.2/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
KeyError: 'RA_score'
```

If I increase the `--motif-pvalue` by one order of magnitude it does not show the error and the files are ok. Is this a simmilar problem than what is being solved in issue "BINDetect p-value issue"? Or is there something i don't see? Thanks a lot!

**Comment by msbentsen** [comment]
This looks like the same error as #15 - could you install the newest `0.11.2` version? That should solve the issue. The updated version will likely warn you that there were motifs with no sites found (e.g. no direct matches in the genome).

**Comment by JavBurgoa** [comment]
That is perfect, Thanks a lot!
