### ISSUE TITLE
Error at TOBIAS ATACorrect

### ISSUE THREAD

**Issue by VenkateshLab** [loosolab/TOBIAS#180]
Hi, I have downloaded the bam and peak bed files from encode proejct https://www.encodeproject.org/experiments/ENCSR310MLB/ and downloaded the mice reference genome mm10 from https://www.ncbi.nlm.nih.gov/assembly/GCF_000001635.20/

While running TOBIAS ATACorrect im getting the following error. i though it might be an installtion issue so i ran the example data set which was provided. i did not get this error. 

`TOBIAS ATACorrect --bam P0.bam --genome ../Refence/mm10.fa --peaks peaks.bed`

```
# TOBIAS 0.14.0 ATACorrect (run started 2023-01-11 10:08:43.030919)
# Working directory: /media/volume/sdf/Manoj/TOBIAS/Test/data
# Command line call: TOBIAS ATACorrect --bam P0.bam --genome ../Refence/mm10.fa --peaks peaks.bed

# ----- Input parameters -----
# bam:	P0.bam
# genome:	../Refence/mm10.fa
# peaks:	peaks.bed
# regions_in:	None
# regions_out:	None
# blacklist:	None
# extend:	100
# split_strands:	False
# norm_off:	False
# track_off:	[]
# drop_chroms:	['chrM', 'chrMT', 'M', 'MT', 'Mito']
# k_flank:	12
# read_shift:	[4, -5]
# bg_shift:	100
# window:	100
# score_mat:	DWM
# prefix:	P0
# outdir:	/media/volume/sdf/Manoj/TOBIAS/Test/data
# cores:	1
# split:	100
# verbosity:	3


# ----- Output files -----
# /media/volume/sdf/Manoj/TOBIAS/Test/data/P0_uncorrected.bw
# /media/volume/sdf/Manoj/TOBIAS/Test/data/P0_bias.bw
# /media/volume/sdf/Manoj/TOBIAS/Test/data/P0_expected.bw
# /media/volume/sdf/Manoj/TOBIAS/Test/data/P0_corrected.bw
# /media/volume/sdf/Manoj/TOBIAS/Test/data/P0_atacorrect.pdf


2023-01-11 10:08:43 (975241) [INFO]	----- Processing input data -----
2023-01-11 10:08:43 (975241) [INFO]	Reading info from .bam file
2023-01-11 10:08:43 (975241) [INFO]	Reading info from .fasta file
2023-01-11 10:08:43 (975241) [INFO]	The following contigs were dropped from analysis because they were found in '--drop-chroms': ['chrM']
2023-01-11 10:08:43 (975241) [INFO]	Processing input/output regions
Traceback (most recent call last):
  File "/home/exouser/miniconda3/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.14.0', 'console_scripts', 'TOBIAS')())
  File "/home/exouser/miniconda3/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/home/exouser/miniconda3/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/tools/atacorrect.py", line 194, in run_atacorrect
    peak_regions = RegionList().from_bed(args.peaks)
  File "/home/exouser/miniconda3/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/utils/regions.py", line 216, in from_bed
    bedlines = open(bedfile_f).readlines()
  File "/home/exouser/miniconda3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Can you help me with this issue. i have tested with multiple bam file still i'm geting this error.

**Comment by msbentsen** [comment]
Hi, thank you for posting the log! The error seems to arise from reading the `--peaks`-file. The input says the ending is `.bed`, but might it actually be `.bed.gz`? If this is the case, could you unzip it and try again with the raw text file? TOBIAS is unfortunately not able to read compressed .bed-files.

**Comment by VenkateshLab** [comment]
@msbentsen thanks its working. my mistake i did not notice it was a gz file.

**Comment by msbentsen** [comment]
Great, happy to help! I will close this issue but feel free to reopen in case of other issues 👍
