### ISSUE TITLE
BINDetect failed for differential analysis

### ISSUE THREAD

**Issue by jibzhang** [loosolab/TOBIAS#182]
I used TOBIAS BINDetect to do differential analysis, it output the motifs bed file and bindetect_results files but failed to make plot file. I merged post-filtered and sorted bam files for replicates, and did ATACorrect and FootprintScores. Then I cat|sort|bedtools merge .narrowpeak file of each samples from MACS2 to make a merged peak file, and annotated the peak file with Homer before this step. Below is my command. 

TOBIAS BINDetect --motifs motif_databases/HUMAN/HOCOMOCOv11_core_HUMAN_mono_meme_format.meme --signals PRDM1_ATAC/nofeeder/ATACseq/TOBIAS/nofeeder_footprints.bw PRDM1_ATAC/feeder/ATACseq/TOBIAS/feeder_footprints.bw --genome refData/genome/human/GRCh38/bwa/GRCh38.fa --peaks PRDM1_ATAC/merged_peaks.annotation.bed --peak-header PRDM1_ATAC/merged_peaks.annotation.header --outdir PRDM1_ATAC/TOBIAS/BINDdetect --cond-names nofeeder feeder --cores 4

It fails with the error for differential analysis. But if I delete one group and leave the other in the command, it worked successfully for single sample. Could you check for me what is the problem? Thanks.

2023-01-17 18:50:48 (1327676) [INFO]	Scanning for motifs and matching to signals...
2023-01-17 18:52:23 (1327676) [INFO]	Progress done!
2023-01-17 18:52:23 (1327676) [INFO]	Done scanning for TFBS across regions!
2023-01-17 18:52:23 (1327676) [INFO]	Waiting for bedfiles to write
2023-01-17 18:52:25 (1327676) [INFO]	Merging results from subsets

2023-01-17 18:52:31 (1327676) [INFO]	Normalizing scores across conditions
2023-01-17 18:52:32 (1327676) [INFO]	Estimating bound/unbound threshold
2023-01-17 18:52:33 (1327676) [STATS]	- Threshold estimated at: 2.00474

2023-01-17 18:52:33 (1327676) [INFO]	Calculating background log2 fold-changes between conditions
2023-01-17 18:52:33 (1327676) [INFO]	- nofeeder / feeder

2023-01-17 18:52:33 (1327676) [INFO]	Processing scanned TFBS individually
2023-01-17 18:59:25 (1327676) [INFO]	Progress 98.5%
2023-01-17 18:59:25 (1327676) [INFO]	Progress 98.75%
/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/tools/bindetect_functions.py:464: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/tools/bindetect_functions.py:464: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
2023-01-17 18:59:26 (1327676) [INFO]	Progress 99.0%
2023-01-17 18:59:27 (1327676) [INFO]	Progress 99.25%
/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/tools/bindetect_functions.py:464: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
2023-01-17 18:59:28 (1327676) [INFO]	Progress 99.5%
/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/tools/bindetect_functions.py:464: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
2023-01-17 18:59:29 (1327676) [INFO]	Progress 99.75%
/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/tools/bindetect_functions.py:464: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
2023-01-17 18:59:32 (1327676) [INFO]	Progress 100.0%
2023-01-17 18:59:32 (1327676) [INFO]	Progress done!
2023-01-17 18:59:32 (1327676) [INFO]	Concatenating results from subsets

2023-01-17 18:59:33 (1327676) [INFO]	Writing all_bindetect files
/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/tools/bindetect.py:733: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  info_table_clustered = info_table.groupby("cluster").mean() 	#mean of each column
/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/tools/bindetect.py:754: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
2023-01-17 18:59:33 (1327676) [INFO]	Creating BINDetect plot(s)
2023-01-17 18:59:33 (1327676) [INFO]	- nofeeder / feeder (static plot)
Traceback (most recent call last):
  File "/home/zgu_labs/anaconda3/envs/ATAC-seq/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.14.0', 'console_scripts', 'TOBIAS')())
  File "/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/tools/bindetect.py", line 819, in run_bindetect
    fig = plot_bindetect(motif_list, clustering, [cond1, cond2], args)
  File "/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/tools/bindetect_functions.py", line 768, in plot_bindetect
    adjust_text(txts, ax=ax1, add_objects=[l], text_from_points=True, arrowprops=dict(arrowstyle='-', color='black', lw=0.5))  #, expand_text=(0.1,1.2), expand_objects=(0.1,0.1))
  File "/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/adjustText-0.8b2-py3.9.egg/adjustText/__init__.py", line 730, in adjust_text
    ax.annotate(
  File "/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 666, in annotate
    a = mtext.Annotation(text, xy, *args, **kwargs)
  File "/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/matplotlib/text.py", line 1825, in __init__
    Text.__init__(self, x, y, text, **kwargs)
  File "/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/matplotlib/text.py", line 160, in __init__
    self.update(kwargs)
  File "/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/matplotlib/text.py", line 172, in update
    super().update(kwargs)
  File "/home/zgu_labs/anaconda3/envs/ATAC-seq/lib/python3.9/site-packages/matplotlib/artist.py", line 1064, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'Annotation' object has no property 'text_from_points'

**Comment by msbentsen** [comment]
Hi, thank you for this error report! I see that this has occurred before, and was solved: https://github.com/loosolab/TOBIAS/issues/116#issuecomment-1032387479

Apparently the installation fetches a beta version of the module adjustText, which causes the error. I fixed this on the dev branch now, but you can fix directly by downgrading adjustText:
`pip install adjusttext==0.7.3`

Let me know in case of any other issues.

**Comment by jibzhang** [comment]
Thank you very much. It worked after downgrading adjustText.
