### ISSUE TITLE
Error message (updated) during BINDetect

### ISSUE THREAD

**Issue by adelosan521** [loosolab/TOBIAS#185]
Hi,

When I run BINDetect there is an error message saying that a file contains NaN, but when I remove NaN from the bw file, I get another error message. Is there a way to fix this? Error messages are below

First time running BINDetect:

Hi, when I try to run BINDetect I get the following error message:

"Traceback (most recent call last):
File "/package/python-cbrg/current/3.10/bin/TOBIAS", line 8, in
sys.exit(main())
File "/package/python-cbrg/current/3.10/lib/python3.10/site-packages/tobias/TOBIAS.py", line 154, in main
args.func(args)
File "/package/python-cbrg/current/3.10/lib/python3.10/site-packages/tobias/tools/bindetect.py", line 480, in run_bindetect
gmm.fit(log_vals)
File "/package/python-cbrg/current/3.10/lib/python3.10/site-packages/sklearn/mixture/_base.py", line 200, in fit
self.fit_predict(X, y)
File "/package/python-cbrg/current/3.10/lib/python3.10/site-packages/sklearn/mixture/_base.py", line 230, in fit_predict
X = self._validate_data(X, dtype=[np.float64, np.float32], ensure_min_samples=2)
File "/package/python-cbrg/current/3.10/lib/python3.10/site-packages/sklearn/base.py", line 577, in _validate_data
X = check_array(X, input_name="X", **check_params)
File "/package/python-cbrg/current/3.10/lib/python3.10/site-packages/sklearn/utils/validation.py", line 899, in check_array
_assert_all_finite(
File "/package/python-cbrg/current/3.10/lib/python3.10/site-packages/sklearn/utils/validation.py", line 146, in _assert_all_finite
raise ValueError(msg_err)
ValueError: Input X contains NaN.
GaussianMixture does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values
2023-01-26 03:47:08 (2237) [ERROR] Multiprocessing logger lost connection to queue - probably due to an error raised from a child process."

I used the following command to remove NaN

sed -i "/NaN/d" filename_corrected.bw

Then I received this second error message:

[readRTreeIDx] Mismatch in the magic number!
[bwOpen] bwg -> idx is NULL bwg ->hdr->dataOffset 0xf0e!
[pyBwOpen] bw is NULL!
Traceback (most recent call last):
   File "/package/python-cbrg/current/3.10/bin/TOBIAS", line 8, in <module>
      sys.exit(main())
   File "/package/python-cbrg/current/3.10/lib/python3.10/site-packages/tobias/TOBIAS.py"
,  line 154, in main
        args.func(args)
    File "/package/python-cbrg/current/3.10/lib/python3.10/site-packages/tobias/tools/bindetect.py", line 211, in run_bindetect
         pybw_obj = pybw.open(signal)
RuntimeError: Received an error during file opening!

Would very much appreciate help!

**Comment by jad362** [comment]
HI @adelosan521 , I see you closed this issue as completed. Would you mind sharing your fix please? I am encountering the same issue currently and would very much appreciate the help!
