### ISSUE TITLE
Installation issue: pyBigWig can't be installed

### ISSUE THREAD

**Issue by Matthionine** [loosolab/TOBIAS#197]
Hello,
I am trying to install TOBIAS on my linux pc (Manjaro with python 3.10.9).
Unfortunately, none of the installation procedures work completely. I tried `pip install tobias --user` as well as installing it directly from github. In both cases the installation fails while installing `pyBigWig` with `AttributeError: 'PathDistribution' object has no attribute 'key'`. (See complete logs further down.)
Is there any way to skip installation of `pyBigWig`?

If I use `pip install tobias` it fails with the following error:

```
pip install tobias --user
Collecting tobias
  Using cached tobias-0.15.1.tar.gz (5.0 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/lib/python3.10/site-packages (from tobias) (1.24.1)
Requirement already satisfied: scipy in /usr/lib/python3.10/site-packages (from tobias) (1.10.0)
Collecting pysam
  Using cached pysam-0.20.0-cp310-cp310-manylinux_2_24_x86_64.whl (15.5 MB)
Collecting pybedtools
  Using cached pybedtools-0.9.0.tar.gz (12.5 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: matplotlib>=2 in /usr/lib/python3.10/site-packages (from tobias) (3.6.2)
Collecting scikit-learn
  Using cached scikit_learn-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.6 MB)
Requirement already satisfied: pandas in /usr/lib/python3.10/site-packages (from tobias) (1.5.3)
Collecting pypdf2
  Using cached pypdf2-3.0.1-py3-none-any.whl (232 kB)
Collecting xlsxwriter
  Using cached XlsxWriter-3.0.8-py3-none-any.whl (152 kB)
Collecting adjustText
  Using cached adjustText-0.8-py3-none-any.whl (9.1 kB)
Collecting pyBigWig>=0.3
  Using cached pyBigWig-0.3.18.tar.gz (64 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      /tmp/pip-install-y2hqy7g7/pybigwig_c31ccef7c90e4f43a9699a31b11ad9ee/setup.py:8: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
        from numpy.distutils.misc_util import get_info
      /usr/lib/python3.10/site-packages/setuptools/dist.py:788: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      /usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'classifier'
        warnings.warn(msg)
      running egg_info
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-y2hqy7g7/pybigwig_c31ccef7c90e4f43a9699a31b11ad9ee/setup.py", line 64, in <module>
          setup(name = 'pyBigWig',
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 253, in finalize_options
          if pd is not None and pd.key == self.egg_name.lower():
      AttributeError: 'PathDistribution' object has no attribute 'key'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

If I try to install it from github directly it runs for a while and fails with the same error:

```
python setup.py install --user                  ±[main]
/usr/lib/python3.10/site-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
  dist.fetch_build_eggs(dist.setup_requires)
running install
/usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing tobias.egg-info/PKG-INFO
writing dependency_links to tobias.egg-info/dependency_links.txt
writing entry points to tobias.egg-info/entry_points.txt
writing requirements to tobias.egg-info/requires.txt
writing top-level names to tobias.egg-info/top_level.txt
reading manifest file 'tobias.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'tobias.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
skipping 'tobias/utils/ngs.c' Cython extension (up-to-date)
skipping 'tobias/utils/sequences.c' Cython extension (up-to-date)
skipping 'tobias/utils/signals.c' Cython extension (up-to-date)
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/tobias
creating build/bdist.linux-x86_64/egg/tobias/utils
copying build/lib.linux-x86_64-cpython-310/tobias/utils/signals.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/tobias/utils
copying build/lib.linux-x86_64-cpython-310/tobias/utils/logger.py -> build/bdist.linux-x86_64/egg/tobias/utils
copying build/lib.linux-x86_64-cpython-310/tobias/utils/sequences.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/tobias/utils
copying build/lib.linux-x86_64-cpython-310/tobias/utils/__init__.py -> build/bdist.linux-x86_64/egg/tobias/utils
copying build/lib.linux-x86_64-cpython-310/tobias/utils/ngs.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/tobias/utils
copying build/lib.linux-x86_64-cpython-310/tobias/utils/regions.py -> build/bdist.linux-x86_64/egg/tobias/utils
copying build/lib.linux-x86_64-cpython-310/tobias/utils/motifs.py -> build/bdist.linux-x86_64/egg/tobias/utils
copying build/lib.linux-x86_64-cpython-310/tobias/utils/utilities.py -> build/bdist.linux-x86_64/egg/tobias/utils
copying build/lib.linux-x86_64-cpython-310/tobias/__init__.py -> build/bdist.linux-x86_64/egg/tobias
copying build/lib.linux-x86_64-cpython-310/tobias/parsers.py -> build/bdist.linux-x86_64/egg/tobias
copying build/lib.linux-x86_64-cpython-310/tobias/TOBIAS.py -> build/bdist.linux-x86_64/egg/tobias
creating build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/maxpos.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/score_bigwig.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/plot_heatmap.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/subsample_bam.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/bindetect.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/format_motifs.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/tfbscan.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/__init__.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/motif_clust.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/atacorrect_functions.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/score_bed.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/create_network.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/plot_aggregate.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/cluster_tfbs.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/filter_fragments.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/log2table.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/atacorrect.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/merge_pdfs.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/plot_changes.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/bindetect_functions.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/download_data.py -> build/bdist.linux-x86_64/egg/tobias/tools
copying build/lib.linux-x86_64-cpython-310/tobias/tools/plot_tracks.py -> build/bdist.linux-x86_64/egg/tobias/tools
byte-compiling build/bdist.linux-x86_64/egg/tobias/utils/logger.py to logger.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/utils/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/utils/regions.py to regions.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/utils/motifs.py to motifs.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/utils/utilities.py to utilities.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/parsers.py to parsers.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/TOBIAS.py to TOBIAS.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/maxpos.py to maxpos.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/score_bigwig.py to score_bigwig.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/plot_heatmap.py to plot_heatmap.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/subsample_bam.py to subsample_bam.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/bindetect.py to bindetect.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/format_motifs.py to format_motifs.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/tfbscan.py to tfbscan.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/motif_clust.py to motif_clust.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/atacorrect_functions.py to atacorrect_functions.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/score_bed.py to score_bed.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/create_network.py to create_network.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/plot_aggregate.py to plot_aggregate.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/cluster_tfbs.py to cluster_tfbs.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/filter_fragments.py to filter_fragments.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/log2table.py to log2table.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/atacorrect.py to atacorrect.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/merge_pdfs.py to merge_pdfs.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/plot_changes.py to plot_changes.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/bindetect_functions.py to bindetect_functions.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/download_data.py to download_data.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/tools/plot_tracks.py to plot_tracks.cpython-310.pyc
creating stub loader for tobias/utils/ngs.cpython-310-x86_64-linux-gnu.so
creating stub loader for tobias/utils/sequences.cpython-310-x86_64-linux-gnu.so
creating stub loader for tobias/utils/signals.cpython-310-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/tobias/utils/ngs.py to ngs.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/utils/sequences.py to sequences.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tobias/utils/signals.py to signals.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.10/cluster_sites_by_overlap.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.10/filter_important_factors.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/cluster_sites_by_overlap.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/filter_important_factors.py to 755
copying tobias.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying tobias.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying tobias.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying tobias.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying tobias.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying tobias.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying tobias.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/tobias-0.15.1-py3.10-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing tobias-0.15.1-py3.10-linux-x86_64.egg
creating /home/matthias/.local/lib/python3.10/site-packages/tobias-0.15.1-py3.10-linux-x86_64.egg
Extracting tobias-0.15.1-py3.10-linux-x86_64.egg to /home/matthias/.local/lib/python3.10/site-packages
Adding tobias 0.15.1 to easy-install.pth file
Installing cluster_sites_by_overlap.py script to /home/matthias/.local/bin
Installing filter_important_factors.py script to /home/matthias/.local/bin
Installing TOBIAS script to /home/matthias/.local/bin

Installed /home/matthias/.local/lib/python3.10/site-packages/tobias-0.15.1-py3.10-linux-x86_64.egg
Processing dependencies for tobias==0.15.1

[...]

Searching for pyBigWig>=0.3
Reading https://pypi.org/simple/pyBigWig/
Downloading https://files.pythonhosted.org/packages/23/29/b51c3580427dd66dfecd63ffbe2dfa37175d3c898b289a3f27def1be34c0/pyBigWig-0.3.18.tar.gz#sha256=4c2a8c571b4100ad7c4c318c142eb48558646be52aaab28215a70426f5be31bc
Best match: pyBigWig 0.3.18
Processing pyBigWig-0.3.18.tar.gz
Writing /tmp/easy_install-ucj3k2fk/pyBigWig-0.3.18/setup.cfg
Running pyBigWig-0.3.18/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ucj3k2fk/pyBigWig-0.3.18/egg-dist-tmp-fw1rs87c
/tmp/easy_install-ucj3k2fk/pyBigWig-0.3.18/setup.py:8: DeprecationWarning: 

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 


  from numpy.distutils.misc_util import get_info
/usr/lib/python3.10/site-packages/setuptools/dist.py:788: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'classifier'
  warnings.warn(msg)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-ucj3k2fk/pyBigWig-0.3.18/setup.py", line 64, in <module>
    entry_points={
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 92, in finalize_options
    ei_cmd = self.ei_cmd = self.get_finalized_command("egg_info")
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 253, in finalize_options
    if pd is not None and pd.key == self.egg_name.lower():
AttributeError: 'PathDistribution' object has no attribute 'key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matthias/Dokumente/Programming/Tobias/TOBIAS/setup.py", line 54, in <module>
    setup(name='tobias',
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/lib/python3.10/site-packages/setuptools/command/install.py", line 131, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 420, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 662, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 709, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 754, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 815, in resolve
    dist = self._resolve_dist(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 851, in _resolve_dist
    dist = best[req.key] = env.best_match(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1135, in obtain
    return installer(requirement)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 681, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 707, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 900, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 1174, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 1158, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 249, in run_setup
    with setup_context(setup_dir):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 190, in setup_context
    with save_modules():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3.10/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-ucj3k2fk/pyBigWig-0.3.18/setup.py", line 64, in <module>
    entry_points={
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 92, in finalize_options
    ei_cmd = self.ei_cmd = self.get_finalized_command("egg_info")
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 253, in finalize_options
    if pd is not None and pd.key == self.egg_name.lower():
AttributeError: 'PathDistribution' object has no attribute 'key'

```

**Comment by Matthionine** [comment]
Installing pyBigWig from [AUR](https://aur.archlinux.org/packages/python-pybigwig)  seems to work.
I guess this issue can be closed then...
