### ISSUE TITLE
Having issue with ploting track.

### ISSUE THREAD

**Issue by mano2991** [loosolab/TOBIAS#200]
While ploting my tracks im getting an error. tried to install wand python package and ImageMagick installation once more still the error pops up.

```
TOBIAS PlotTracks --bigwigs *_corrected.bw --bigwigs *_footprints.bw --regions test_region.bed --sites test_site.bed --highlight test_site.bed --gtf mm38.gtf --colors red darkblue green red darkblue green
# TOBIAS 0.14.0 PlotTracks (run started 2023-03-15 09:07:40.196093)
# Working directory: /media/volume/sdf/Manoj/TOBIAS/Test/TOBIAS_snakemake/binddetect
# Command line call: TOBIAS PlotTracks --bigwigs Adult_corrected.bw Embroyo_corrected.bw Postnatal_corrected.bw --bigwigs Adult_footprints.bw Embroyo_footprints.bw Postnatal_footprints.bw --regions test_region.bed --sites test_site.bed --highlight test_site.bed --gtf mm38.gtf --colors red darkblue green red darkblue green

# ----- Input parameters -----
# bigwigs:      [['Adult_corrected.bw', 'Embroyo_corrected.bw', 'Postnatal_corrected.bw'], ['Adult_footprints.bw', 'Embroyo_footprints.bw', 'Postnatal_footprints.bw']]
# regions:      test_region.bed
# sites:        test_site.bed
# highlight:    test_site.bed
# gtf:  mm38.gtf
# width:        15
# colors:       ['red', 'darkblue', 'green', 'red', 'darkblue', 'green']
# labels:       None
# max_transcripts:      1
# outdir:       plottracks_output
# verbosity:    3


2023-03-15 09:07:40 (314780) [INFO]     Plotting region: ['chr14', '34133406', '34133923']
Traceback (most recent call last):
  File "/home/exouser/miniconda3/lib/python3.9/site-packages/svist4get-1.3.1-py3.9.egg/svist4get/methods.py", line 37, in pdf_page_to_png
    page = Image(filename=filename, resolution=resolution)
  File "/home/exouser/miniconda3/lib/python3.9/site-packages/Wand-0.6.10-py3.9.egg/wand/image.py", line 9326, in __init__
    self.read(filename=filename)
  File "/home/exouser/miniconda3/lib/python3.9/site-packages/Wand-0.6.10-py3.9.egg/wand/image.py", line 10075, in read
    self.raise_exception()
  File "/home/exouser/miniconda3/lib/python3.9/site-packages/Wand-0.6.10-py3.9.egg/wand/resource.py", line 225, in raise_exception
    raise e
wand.exceptions.PolicyError: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/exouser/miniconda3/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.14.0', 'console_scripts', 'TOBIAS')())
  File "/home/exouser/miniconda3/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/TOBIAS.py", line 154, in main
    args.func(args)
  File "/home/exouser/miniconda3/lib/python3.9/site-packages/tobias-0.14.0-py3.9-linux-x86_64.egg/tobias/tools/plot_tracks.py", line 387, in run_tracks
    sv4g.methods.pdf_page_to_png(pa)    #pdf to png
  File "/home/exouser/miniconda3/lib/python3.9/site-packages/svist4get-1.3.1-py3.9.egg/svist4get/methods.py", line 58, in pdf_page_to_png
    raise Svist4getError('Unable to convert the pdf file to png. There might be a problem with the \'wand\' python package or with ImageMagick installation.') from error
svist4get.methods.Svist4getError: Unable to convert the pdf file to png. There might be a problem with the 'wand' python package or with ImageMagick installation.
```

**Comment by mano2991** [comment]
fixed this issue by changing the policy.xml file in terminal by entering this command -

`sudo nano /etc/ImageMagick-6/policy.xml`
Now, directly edit the file in terminal, find 
`<policy domain="coder" rights="none" pattern="PDF" /> and replace none with read|write` 
as shown in the picture.
Then press `Ctrl+X` to exit.
![image](https://user-images.githubusercontent.com/13638496/225282339-cdb68707-0e4c-4712-b701-bfd97af0f7b1.png)

Now new error pops up 

```
TOBIAS PlotTracks --bigwigs *_corrected.bw --bigwigs *_footprints.bw --regions test_region.bed --sites test_site.bed --highlight test_site.bed --gtf mm38.gtf --colors red darkblue green red darkblue green

# TOBIAS 0.15.1 PlotTracks (run started 2023-03-15 15:58:37.992583)
# Working directory: /home/ivlab/Documents/binddetect
# Command line call: TOBIAS PlotTracks --bigwigs Adult_corrected.bw Embroyo_corrected.bw Postnatal_corrected.bw --bigwigs Adult_footprints.bw Embroyo_footprints.bw Postnatal_footprints.bw --regions test_region.bed --sites test_site.bed --highlight test_site.bed --gtf mm38.gtf --colors red darkblue green red darkblue green

# ----- Input parameters -----
# bigwigs:	[['Adult_corrected.bw', 'Embroyo_corrected.bw', 'Postnatal_corrected.bw'], ['Adult_footprints.bw', 'Embroyo_footprints.bw', 'Postnatal_footprints.bw']]
# regions:	test_region.bed
# sites:	test_site.bed
# highlight:	test_site.bed
# gtf:	mm38.gtf
# width:	15
# colors:	['red', 'darkblue', 'green', 'red', 'darkblue', 'green']
# labels:	None
# max_transcripts:	1
# outdir:	plottracks_output
# verbosity:	3


2023-03-15 15:58:37 (1316699) [INFO]	Plotting region: ['chr14', '34133406', '34133923']
Traceback (most recent call last):
  File "/home/ivlab/miniconda3/bin/TOBIAS", line 8, in <module>
    sys.exit(main())
  File "/home/ivlab/miniconda3/lib/python3.10/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/home/ivlab/miniconda3/lib/python3.10/site-packages/tobias/tools/plot_tracks.py", line 391, in run_tracks
    merger = PdfFileMerger(strict=False)
  File "/home/ivlab/miniconda3/lib/python3.10/site-packages/PyPDF2/_merger.py", line 817, in __init__
    deprecation_with_replacement("PdfFileMerger", "PdfMerger", "3.0.0")
  File "/home/ivlab/miniconda3/lib/python3.10/site-packages/PyPDF2/_utils.py", line 369, in deprecation_with_replacement
    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))
  File "/home/ivlab/miniconda3/lib/python3.10/site-packages/PyPDF2/_utils.py", line 351, in deprecation
    raise DeprecationError(msg)
PyPDF2.errors.DeprecationError: PdfFileMerger is deprecated and was removed in PyPDF2 3.0.0. Use PdfMerger instead.

```

**Comment by mano2991** [comment]
Insalling PyPDF2<3.0 fixed the issue. 

`pip install 'PyPDF2<3.0'`

Now i cant plot more than one foot prints in my bed file it shows an error. if i give two location at my bed files 

```
TOBIAS PlotTracks --bigwigs *_corrected.bw --bigwigs *_footprints.bw --regions test_region.bed --sites test_site.bed --highlight test_site.bed --gtf mm38.gtf --colors red darkblue green red darkblue green 

# TOBIAS 0.15.1 PlotTracks (run started 2023-03-15 16:09:38.135905)
# Working directory: /home/ivlab/Documents/binddetect
# Command line call: TOBIAS PlotTracks --bigwigs Adult_corrected.bw Embroyo_corrected.bw Postnatal_corrected.bw --bigwigs Adult_footprints.bw Embroyo_footprints.bw Postnatal_footprints.bw --regions test_region.bed --sites test_site.bed --highlight test_site.bed --gtf mm38.gtf --colors red darkblue green red darkblue green --max-transcripts 40

# ----- Input parameters -----
# bigwigs:	[['Adult_corrected.bw', 'Embroyo_corrected.bw', 'Postnatal_corrected.bw'], ['Adult_footprints.bw', 'Embroyo_footprints.bw', 'Postnatal_footprints.bw']]
# regions:	test_region.bed
# sites:	test_site.bed
# highlight:	test_site.bed
# gtf:	mm38.gtf
# width:	15
# colors:	['red', 'darkblue', 'green', 'red', 'darkblue', 'green']
# labels:	None
# max_transcripts:    1
# outdir:	plottracks_output
# verbosity:	3


2023-03-15 16:09:38 (1318885) [INFO]	Plotting region: ['chr8', '70760373', '70761483']
Traceback (most recent call last):
  File "/home/ivlab/miniconda3/bin/TOBIAS", line 8, in <module>
    sys.exit(main())
  File "/home/ivlab/miniconda3/lib/python3.10/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/home/ivlab/miniconda3/lib/python3.10/site-packages/tobias/tools/plot_tracks.py", line 299, in run_tracks
    pa.config['genomic_intervals_label'] = [site[3] for site in sites_in_region]
  File "/home/ivlab/miniconda3/lib/python3.10/site-packages/tobias/tools/plot_tracks.py", line 299, in <listcomp>
    pa.config['genomic_intervals_label'] = [site[3] for site in sites_in_region]
  File "pybedtools/cbedtools.pyx", line 524, in pybedtools.cbedtools.Interval.__getitem__
IndexError: field index out of range
```

**Comment by mano2991** [comment]
If im not provinding the --sites argument im getting the images, but i cant able to see the transcript factor name in the image. while using UCSC brower i can able to visulaize the transcipt factor which are located in those site. 
![chr13-34130747-34132466](https://user-images.githubusercontent.com/13638496/225324443-8b0bafca-98df-4ab3-8de3-4b109fcea0df.png)

ucsc brower image
![image](https://user-images.githubusercontent.com/13638496/225325135-83bd9bf6-73ca-4d5a-b171-0a4d680cca4b.png)

**Comment by msbentsen** [comment]
Hi @mano2991 ,

Thank you for your issue! How does your `--sites` file look? From the error, it looks like it is missing the fourth "name" column. Can you try to add a column with a label?

It should be able to work without the name though, so I will label this as a bug for us to create a fix. Sorry for the problems!

**Comment by mano2991** [comment]
@msbentsen  yes it working if i give the Transcript name in the bed file. at the 4th colum. 

![chr13-34131398-34132013](https://user-images.githubusercontent.com/13638496/226247423-113c48ec-34ca-4c1c-b790-f74e9e06b5a9.png)
