### ISSUE TITLE
BINDetect - 'Annotation' object has no property 'text_from_points' only for time series 

### ISSUE THREAD

**Issue by sngholee** [loosolab/TOBIAS#269]
Hello,

I'm getting this issue w/ BINDetct. I've tried downgrading adjusttext but still get this error message. This issue only arises when I do the time series, and running on single timepoints does not give any issues. I can't view the pdf output from the output when I try the time series. However, the other outputs (bindetect_results, bindetect_distances) seem fine. I'd appreciate any suggestions.

Code attempted:
```
TOBIAS BINDetect --motifs ${JASPAR} --signals ${BIGWIGS}/Lo_{0,2,24,48,72}_REP2_score.bw $i  --genome \ /public/groups/shariatilab/slee/RefGenomes/mm10.fa --peaks \ /public/groups/shariatilab/slee/MEKiRound3/ATACSeq/redo/consensusPeaks/consensusPeaksBEDCoordsOnly.txt \ --outdir ${OUTDIR}/ --time-series --cores 12

The error message:
Traceback (most recent call last): File "/public/home/slee393/miniconda3/bin/TOBIAS",
 line 33, in <module> sys.exit(load_entry_point('tobias==0.16.1', 'console_scripts', 'TOBIAS')()) 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/tobias-0.16.1-py3.11-linux-x86_64.egg/tobias/TOBIAS.py", 
line 162, in main args.func(args) 
^^^^^^^^^^^^^^^ 
File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/tobias-0.16.1-py3.11-linux-x86_64.egg/tobias/tools/bindetect.py",
 line 819, in run_bindetect fig = plot_bindetect(motif_list, clustering, [cond1, cond2], args) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/tobias-0.16.1-py3.11-linux-x86_64.egg/tobias/tools/bindetect_functions.py", 
line 773, in plot_bindetect adjust_text(txts, ax=ax1, add_objects=[l], text_from_points=True, arrowprops=dict(arrowstyle='-', color='black', lw=0.5))  #, expand_text=(0.1,1.2), expand_objects=(0.1,0.1)) 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/adjustText/__init__.py", 
line 730, in adjust_text ax.annotate(
 File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/axes/_axes.py",
 line 711, in annotate a = mtext.Annotation(text, xy, xytext=xytext, xycoords=xycoords, 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/text.py",
 line 1845, in __init__ Text.__init__(self, x, y, text, **kwargs)
 File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/text.py",
 line 155, in __init__ self.update(kwargs)
 File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/text.py",
 line 205, in update ret.extend(super().update(kwargs)) 
^^^^^^^^^^^^^^^^^^^^^^ 
File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/artist.py",
 line 1209, in update return self._update_props( 
^^^^^^^^^^^^^^^^^^^
 File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/artist.py", 
line 1193, in _update_props raise AttributeError( AttributeError: 'Annotation' object has no property 'text_from_points'
```

Thank you

**Comment by mohobein** [comment]
Hey @sngholee,

sorry for the late reply. I tried reproducing the error with the test data and was able to find a solution for it. The fix will be part of the next full release, but if you want to try it out already, you can install the dev branch via `pip install git+https://github.com/loosolab/TOBIAS@dev`. You might need to run `pip install numpy cython` in your environment beforehand. 

I hope this fixes your problem. If not, we can look into it more closely.

Best regards,
Moritz

**Comment by sngholee** [comment]
Hello,

Thank you for looking into this. I tried installing the dev branch and reran the same code for time series, and got the below:

`2024-05-22 15:17:14 (3017104) [INFO]    Creating BINDetect plot(s)
2024-05-22 15:17:14 (3017104) [INFO]    - Lo_0_REP2_score / Lo_2_REP2_score (static plot)
Traceback (most recent call last):
  File "/public/home/slee393/miniconda3/bin/TOBIAS", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/tobias/TOBIAS.py", line 162, in main
    args.func(args)
    ^^^^^^^^^^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/tobias/tools/bindetect.py", line 824, in run_bindetect
    fig = plot_bindetect(motif_list, clustering, [cond1, cond2], args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/tobias/tools/bindetect_functions.py", line 776, in plot_bindetect
    adjust_text(txts, ax=ax1, objects=[l], arrowprops=dict(arrowstyle='-', color='black', lw=0.5))  #, expand_text=(0.1,1.2), expand_objects=(0.1,0.1))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/adjustText/__init__.py", line 730, in adjust_text
    ax.annotate(
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 711, in annotate
    a = mtext.Annotation(text, xy, xytext=xytext, xycoords=xycoords,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/text.py", line 1845, in __init__
    Text.__init__(self, x, y, text, **kwargs)
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/text.py", line 155, in __init__
    self.update(kwargs)
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/text.py", line 205, in update
    ret.extend(super().update(kwargs))
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/artist.py", line 1209, in update
    return self._update_props(
           ^^^^^^^^^^^^^^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/artist.py", line 1193, in _update_props
    raise AttributeError(
AttributeError: 'Annotation' object has no property 'objects'
`

**Comment by mohobein** [comment]
My bad, I forgot to mention this. `adjustText` is still downgraded in your environment from your earlier attempt at fixing it, right? The library changed multiple parameter names between versions, so with the newest TOBIAS version, you also need a version of `adjustText` post these changes. Can you try updating `adjustText` to the newest version and check if the issue persists? For me, it works with version `1.1.1`.

**Comment by sngholee** [comment]
This worked, thank you!
