### ISSUE TITLE
pip install and cython compile errors 

### ISSUE THREAD

**Issue by tjparnell** [loosolab/TOBIAS#297]
I am trying to install this into a python virtual environment using `pip`. This was tried under Python 3.10, 3.11, and 3.12 on two different servers with similar but different Linux distros; all failed. I have tried both version 0.17.0 from PyPi as well as a fresh pull from GitHub, with same errors.

Below is the stack trace using `pip` from PyPI.

```
Collecting tobias
  Using cached tobias-0.17.0.tar.gz (416 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  × Getting requirements to build wheel did not run successfully.
   exit code: 1
  ─> [65 lines of output]
      <string>:11: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try 'pip install --use-pep517'.
              ********************************************************************************
      !!
      /path/tobias-0.17.0/bin/python3: No module named pip
      Traceback (most recent call last):
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'numpy'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-yfe3dsmy/overlay/lib/python3.11/site-packages/setuptools/installer.py", line 107, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/usr/local/Python/3.11/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/path/tobias-0.17.0/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpyw8ek9fb', '--quiet', 'numpy']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/path/tobias-0.17.0/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/path/tobias-0.17.0/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/path/tobias-0.17.0/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-yfe3dsmy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-yfe3dsmy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-yfe3dsmy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-yfe3dsmy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
        File "/tmp/pip-build-env-yfe3dsmy/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 659, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-yfe3dsmy/overlay/lib/python3.11/site-packages/setuptools/installer.py", line 44, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-yfe3dsmy/overlay/lib/python3.11/site-packages/pkg_resources/__init__.py", line 892, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-yfe3dsmy/overlay/lib/python3.11/site-packages/pkg_resources/__init__.py", line 928, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-yfe3dsmy/overlay/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1266, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-yfe3dsmy/overlay/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1302, in obtain
          return installer(requirement) if installer else None
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-yfe3dsmy/overlay/lib/python3.11/site-packages/setuptools/installer.py", line 109, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/path/tobias-0.17.0/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpyw8ek9fb', '--quiet', 'numpy']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
 exit code: 1
─> See above for output.

```

The sub-process appears to be trying to build a wheel for `numpy`, which appears to succeed (the file is written), but is being returned as an error for some reason.

I have tried installing all the prerequisite dependencies (gleaned from the `setup.py` script and `tobias_env.yaml` file) up front, but it still fails. (By the way, these are different lists.)

Furthermore, when I try to bypass `pip` and run `python3 ./setup.py build` directly, I get a completely different error while attempting to compile a cython module. Again, this error is repeatable with all 3 versions of Python. The relevant error is below

```
Compiling tobias/utils/ngs.pyx because it changed.
[1/1] Cythonizing tobias/utils/ngs.pyx
building 'tobias.utils.ngs' extension
creating build/temp.linux-x86_64-cpython-311
creating build/temp.linux-x86_64-cpython-311/tobias
creating build/temp.linux-x86_64-cpython-311/tobias/utils
gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/path/tobias-0.17.0/lib/python3.11/site-packages/numpy/_core/include -I/path/tobias-0.17.0/include -I/usr/local/Python/3.11/include/python3.11 -c tobias/utils/ngs.c -o build/temp.linux-x86_64-cpython-311/tobias/utils/ngs.o
In file included from /path/tobias-0.17.0/lib/python3.11/site-packages/numpy/_core/include/numpy/ndarraytypes.h:1909,
                 from /path/tobias-0.17.0/lib/python3.11/site-packages/numpy/_core/include/numpy/ndarrayobject.h:12,
                 from /path/tobias-0.17.0/lib/python3.11/site-packages/numpy/_core/include/numpy/arrayobject.h:5,
                 from tobias/utils/ngs.c:1249:
/path/tobias-0.17.0/lib/python3.11/site-packages/numpy/_core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
gcc -shared build/temp.linux-x86_64-cpython-311/tobias/utils/ngs.o -o build/lib.linux-x86_64-cpython-311/tobias/utils/ngs.cpython-311-x86_64-linux-gnu.so
Compiling tobias/utils/sequences.pyx because it changed.
[1/1] Cythonizing tobias/utils/sequences.pyx

Error compiling Cython file:
------------------------------------------------------------
...
		#Added by prepare_mat
		self.pssm = np.zeros((5, length)) 	#ATCGN

	@cython.boundscheck(False)
	@cython.wraparound(False)
	def add_sequence(self, np.ndarray[np.int_t, ndim=1] sequence, double amount = 1.0):
                                      ^
------------------------------------------------------------

tobias/utils/sequences.pyx:63:38: Invalid type.
Traceback (most recent call last):
  File "/home/u0462865/packages/TOBIAS-main/./setup.py", line 54, in <module>
    setup(name='tobias',
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 130, in build_extension
    new_ext = cythonize(
              ^^^^^^^^^^
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/path/tobias-0.17.0/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: tobias/utils/sequences.pyx

``` 

Any guidance is appreciated.

**Comment by hschult** [comment]
Hi @tjparnell,
thanks for notifying us!

Indeed there seems to be a problem with the tobias installation process. However, my testing suggests that it is unrelated to the virtual environment. I will investigate and let you know when we have a solution.

In the meantime, if you have any information that may help solve this please don't hesitate to write!

**Comment by hschult** [comment]
The error was due to the package relying on a deprecated c-numpy API. I have updated it now and added it to our dev branch. You can install the dev version using `pip install git+https://github.com/loosolab/TOBIAS.git@dev`. I will do a proper release soon.

Please let me know if there are any more issues.

**Comment by tjparnell** [comment]
Thanks @hschult, the dev branch installed without issues under Python 3.11.

**Comment by hschult** [comment]
So that you know, I did the new release. It should be available on pypi and conda soon.
