### ISSUE TITLE
multiprocessing pool error

### ISSUE THREAD

**Issue by haibol2016** [loosolab/TOBIAS#38]
Hello,

   I used the v0.11.1 tobias BINDdetect to differential binding activities of transcription factors between two conditions. I got the following error. Could you please help with figure it out the reason? Thank you very much.

Haibo

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/hl84w/work/mccb/bin/miniconda2/envs/TOBIAS/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/hl84w/work/mccb/bin/miniconda2/envs/TOBIAS/lib/python3.7/site-packages/tobias/tools/bindetect_functions.py", line 197, in scan_and_score
    raise Exception
Exception
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hl84w/work/mccb/bin/miniconda2/envs/TOBIAS/bin/TOBIAS", line 11, in <module>
    load_entry_point('tobias==0.11.1', 'console_scripts', 'TOBIAS')()
  File "/home/hl84w/work/mccb/bin/miniconda2/envs/TOBIAS/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)
  File "/home/hl84w/work/mccb/bin/miniconda2/envs/TOBIAS/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 312, in run_bindetect
    results = [task.get() for task in task_list]
  File "/home/hl84w/work/mccb/bin/miniconda2/envs/TOBIAS/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 312, in <listcomp>
    results = [task.get() for task in task_list]
  File "/home/hl84w/work/mccb/bin/miniconda2/envs/TOBIAS/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
Exception

**Comment by msbentsen** [comment]
Hi,
Thank you for your issue. To be able to help, I am going to need a little bit more information about the run. Can you post the full log + stderr here? Also, does this error occur with the test data or only when using your own data? Thanks!

**Comment by haibol2016** [comment]
Hello Mette,

   Thank you very much for your timely response.
    I have figured it out. it was due to one line of the BED file is out of
chromosome range.

Thanks again.
Best,

Haibo

**Comment by msbentsen** [comment]
Great that you figured it out - I am closing this, but please reopen in case of any other problems.
