### ISSUE TITLE
Error when running BINDetect

### ISSUE THREAD

**Issue by Rosmaninho** [loosolab/TOBIAS#42]
I ran (TOBIAS 0.11.3) BINDetect with the following parameters: 

`TOBIAS BINDetect --motifs /motifs_dir/pwm_motifs.txt --signals /footprints_dir/cell1_footprints.bw /footprints2_dir/cell2_footprints.bw --genome /genome_dir/hg38.fa.gz --peaks //bed_files/peaks_all/macs2atac_mergedpeaks_PID4_no_hd.bed --peak_header /bed_files/peaks_all/headers.txt --outdir /tobias/diff_bind --cond_names tTreg tTconv --cores 40
`
And got the following error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/site-packages/tobias/tools/bindetect_functions.py", line 391, in process_tfbs
    subset.loc[:,"peak_id"] = ["_".join([chrom, str(start), str(end)]) for (chrom, start, end) in zip(subset["peak_chr"].values, subset["peak_start"].values, subset["peak_end"].values)]
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'peak_chr'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/TOBIAS", line 11, in <module>
    load_entry_point('tobias==0.11.3', 'console_scripts', 'TOBIAS')()
  File "/usr/local/lib/python3.6/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/usr/local/lib/python3.6/site-packages/tobias/tools/bindetect.py", line 545, in run_bindetect
    results = [task.get() for task in task_list]
  File "/usr/local/lib/python3.6/site-packages/tobias/tools/bindetect.py", line 545, in <listcomp>
    results = [task.get() for task in task_list]
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
KeyError: 'peak_chr'
srun: error: compute-18: task 0: Exited with exit code 1
srun: Terminating job step 1296233.0`

Also, the pdf files (bindetect_figures.pdf and motif_log2fcs.pdf files) came out corrupted and when I try to open them with any pdf editor I get the following error:

Error[PXCLib]: Required value not found.

Is this an error specific to this version? We are in the process of updating to 0.12.4 and will try again and report back.

**Comment by Rosmaninho** [comment]
Got the following error with 0.12.4:

`2020-11-24 12:22:46 (53042) [INFO]	----- Processing input data -----
2020-11-24 12:22:46 (53042) [INFO]	Checking reading/writing of files
2020-11-24 12:22:47 (53042) [INFO]	Reading peaks
2020-11-24 12:22:48 (53042) [INFO]	- Found 188169 regions in input peaks
2020-11-24 12:22:48 (53042) [INFO]	- Merged to 188169 regions
2020-11-24 12:22:48 (53042) [INFO]	Checking for match between --peaks and --fasta/--signals boundaries
2020-11-24 12:22:48 (53042) [INFO]	- Comparing peaks to /mnt/nfs/lobo/AESOUSA-NFS/pedro.rosmaninho/bed_files/peaks_all/hg38.fa.gz
2020-11-24 12:22:48 (53042) [INFO]	- Comparing peaks to /mnt/nfs/lobo/AESOUSA-NFS/pedro.rosmaninho/tobias/treg_sbw/treg_footprints.bw
2020-11-24 12:22:49 (53042) [INFO]	- Comparing peaks to /mnt/nfs/lobo/AESOUSA-NFS/pedro.rosmaninho/tobias/tconv_sbw/tconv_footprints.bw
2020-11-24 12:22:49 (53042) [INFO]	Estimating GC content from peak sequences
2020-11-24 12:22:50 (53042) [INFO]	- GC content estimated at 52.77%
2020-11-24 12:22:50 (53042) [INFO]	Reading motifs from file
Traceback (most recent call last):
  File "/usr/local/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.12.4', 'console_scripts', 'TOBIAS')())
  File "/usr/local/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/usr/local/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 213, in run_bindetect
    motif_list += MotifList().from_file(f)  #List of OneMotif objects
  File "/usr/local/lib/python3.7/site-packages/tobias/utils/motifs.py", line 226, in from_file
    self[-1].set_counts(count_matrix)	#this also checks for format
  File "/usr/local/lib/python3.7/site-packages/tobias/utils/motifs.py", line 971, in set_counts
    raise ValueError("Input counts must be of length 4. Received length {0}".format(len(counts)))
ValueError: Input counts must be of length 4. Received length 0
srun: error: compute-18: task 0: Exited with exit code 1
srun: Terminating job step 1296353.0`

**Comment by msbentsen** [comment]
Hi, thank you for your issue.

For the first error (KeyError: 'peak_chr'), I have not seen that before, so I will have to investigate in a bit more detail.

For the second error, is it possible for you to share the motif file that you are using? The error points to an error reading the motif file, so I would be interest to see why it fails.

**Comment by Rosmaninho** [comment]
[pwm_motifs.txt](https://github.com/loosolab/TOBIAS/files/5590176/pwm_motifs.txt)

Sure! This is the file that I am using.
As for the first might it be that the image is missing the software required to make the charts?

**Comment by Rosmaninho** [comment]
Version 0.11.3 works ok. Version 0.12.4 does not. To try 0.12.3 I'll have to wait a bit longer.

**Comment by Rosmaninho** [comment]
We are using the following image: quay.io/biocontainers/tobias:0.12.4--py37h97743b1_0

**Comment by Rosmaninho** [comment]
What is the difference between
quay.io/biocontainers/tobias:0.12.4--py37h97743b1_0 and quay.io/biocontainers/tobias:0.12.4--py36h29c9776_0 ?

**Comment by jenzopr** [comment]
Its the python version, as indicated in the tag name: First image is python 3.7, second python 3.6

**Comment by Rosmaninho** [comment]
Could that influence why I am not being able to use one?

**Comment by Rosmaninho** [comment]
Ok, they both fail. Error at same point:

2020-11-24 15:58:01 (96783) [INFO]	----- Processing input data -----
2020-11-24 15:58:01 (96783) [INFO]	Checking reading/writing of files
2020-11-24 15:58:01 (96783) [INFO]	Reading peaks
2020-11-24 15:58:03 (96783) [INFO]	- Found 188169 regions in input peaks
2020-11-24 15:58:03 (96783) [INFO]	- Merged to 188169 regions
2020-11-24 15:58:03 (96783) [INFO]	Checking for match between --peaks and --fasta/--signals boundaries
2020-11-24 15:58:03 (96783) [INFO]	- Comparing peaks to /mnt/nfs/lobo/AESOUSA-NFS/pedro.rosmaninho/bed_files/peaks_all/hg38.fa.gz
2020-11-24 15:58:03 (96783) [INFO]	- Comparing peaks to /mnt/nfs/lobo/AESOUSA-NFS/pedro.rosmaninho/tobias/treg_sbw/treg_footprints.bw
2020-11-24 15:58:04 (96783) [INFO]	- Comparing peaks to /mnt/nfs/lobo/AESOUSA-NFS/pedro.rosmaninho/tobias/tconv_sbw/tconv_footprints.bw
2020-11-24 15:58:04 (96783) [INFO]	Estimating GC content from peak sequences
2020-11-24 15:58:05 (96783) [INFO]	- GC content estimated at 52.77%
2020-11-24 15:58:05 (96783) [INFO]	Reading motifs from file
Traceback (most recent call last):
  File "/usr/local/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.12.3', 'console_scripts', 'TOBIAS')())
  File "/usr/local/lib/python3.6/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/usr/local/lib/python3.6/site-packages/tobias/tools/bindetect.py", line 213, in run_bindetect
    motif_list += MotifList().from_file(f)  #List of OneMotif objects
  File "/usr/local/lib/python3.6/site-packages/tobias/utils/motifs.py", line 226, in from_file
    self[-1].set_counts(count_matrix)	#this also checks for format
  File "/usr/local/lib/python3.6/site-packages/tobias/utils/motifs.py", line 971, in set_counts
    raise ValueError("Input counts must be of length 4. Received length {0}".format(len(counts)))
ValueError: Input counts must be of length 4. Received length 0
srun: error: compute-2: task 0: Exited with exit code 1
srun: Terminating job step 1296552.0

**Comment by Rosmaninho** [comment]
Going back to a more stable version of TOBIAS - 0.11.6-py37 - it manages to read my pwm.txt file.  However, it gave me this error:

2020-11-24 16:31:54 (98764) [INFO]	Progress 100.0%
2020-11-24 16:31:54 (98764) [INFO]	Progress done!
2020-11-24 16:31:56 (98940) [ERROR]	Multiprocessing logger lost connection to queue - probably due to an error raised from a child process.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2889, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 97, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'peak_chr'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/tobias/tools/bindetect_functions.py", line 392, in process_tfbs
    subset.loc[:,"peak_id"] = ["_".join([chrom, str(start), str(end)]) for (chrom, start, end) in zip(subset["peak_chr"].values, subset["peak_start"].values, subset["peak_end"].values)]
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2891, in get_loc
    raise KeyError(key) from err
KeyError: 'peak_chr'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.11.6', 'console_scripts', 'TOBIAS')())
  File "/usr/local/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/usr/local/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 547, in run_bindetect
    results = [task.get() for task in task_list]
  File "/usr/local/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 547, in <listcomp>
    results = [task.get() for task in task_list]
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
KeyError: 'peak_chr'
srun: error: compute-2: task 0: Exited with exit code 1
srun: Terminating job step 1296647.0

I am having errors at distinct steps in 0.11 and 0.12 with both python versions. The bindetect.pdf cannot be opened in the runs done with 0.11.

**Comment by Rosmaninho** [comment]
When using a pwm_motifs.jaspar motif file (in jaspar format) it actually runs but it hits on the same error as 0.11.x and the bindetect_figures.pdf cannot be opened.
[bindetect_figures.pdf](https://github.com/loosolab/TOBIAS/files/5591869/bindetect_figures.pdf)

2020-11-24 17:54:14 (122356) [INFO]	Progress done!
2020-11-24 17:54:14 (122609) [ERROR]	Multiprocessing logger lost connection to queue - probably due to an error raised from a child process.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'peak_chr'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/tobias/tools/bindetect_functions.py", line 459, in process_tfbs
    subset.loc[:,"peak_id"] = ["_".join([chrom, str(start), str(end)]) for (chrom, start, end) in zip(subset["peak_chr"].values, subset["peak_start"].values, subset["peak_end"].values)]
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'peak_chr'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.12.3', 'console_scripts', 'TOBIAS')())
  File "/usr/local/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/usr/local/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 596, in run_bindetect
    results = [task.get() for task in task_list]
  File "/usr/local/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 596, in <listcomp>
    results = [task.get() for task in task_list]
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
KeyError: 'peak_chr'
srun: error: compute-4: task 0: Exited with exit code 1
srun: Terminating job step 1296781.0

**Comment by msbentsen** [comment]
Hi, 
I have just released `TOBIAS 0.12.5`, which should solve this problem. The issue was that your motifs contain scientific notation (e.g. 1e-5), which were not properly read by TOBIAS - but this has now been adjusted. The version is available on PyPI now, will probably be on bioconda some time today/tomorrow, and then it should automatically update to quay.io.

I believe that the `KeyError: 'peak_chr'` is related to the error of the motifs, but please let me know if this error still occurs for you after updating. Thanks!

**Comment by Rosmaninho** [comment]
My colleague and I found the problem for this last issue.
Apparently, your code in bindetect.py requires the header.txt file in line 176 reads the following:
else:
		args.peak_header_list = ["peak_chr", "peak_start", "peak_end"] + ["additional_" + str(num + 1) for num in range(peak_columns-3)]
	logger.debug("Peak header list: {0}".format(args.peak_header_list))

So I changed my header.txt file from "chr" "start" "stop" to "peak_chr", "peak_start", "peak_end" and now I am getting results.
You should clarify in the wiki for BINDetect that the header.txt first three columns have to be written like that.

**Comment by msbentsen** [comment]
You are right, thank you for making me aware of this! It was not meant to be restricted like that, so I have made some changes to accommodate custom column names for chr, start, end-columns. Please find `TOBIAS 0.12.6` for this fix.

Best Mette

**Comment by apal6** [comment]
Hi,

I get the following error but I am not sure if its due to version issues:

`2025-02-20 15:10:43 (111680) [INFO]	Done scanning for TFBS across regions!
2025-02-20 15:10:43 (111680) [INFO]	Waiting for bedfiles to write
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/share/software/user/open/python/3.12.1/lib/python3.12/multiprocessing/pool.py", line 125, in worker
  File "/home/users/apal6/.local/lib/python3.12/site-packages/tobias/utils/utilities.py", line 98, in file_writer
  File "/home/users/apal6/.local/lib/python3.12/site-packages/tobias/utils/utilities.py", line 95, in file_writer
OSError: [Errno 24] Too many open files: '/tobias_footprinting_results/BINDetect_output/SPL14_MA0586.3/beds/SPL14_MA0586.3.tmp'
"""`

code: 
`TOBIAS BINDetect --motifs /ATAC-seq/external_data/JASPAR2024_CORE_non-redundant_pfms_meme.txt --signals /ATAC-seq/results3/bwa/merged_replicate/tobias_footprinting_results/test.bw --genome /ATAC-seq/results3/genome/genome.fa --peaks /ATAC-seq/results3/bwa/merged_replicate/macs2/narrow_peak/test.mRp.clN_summits.bed --outdir /ATAC-seq/results3/bwa/merged_replicate/tobias_footprinting_results/BINDetect_output --cores 8`

I do see alot of output files being generated but not sure what it means by "Too many open files"? Can you help in debugging?

Thank you so much!
