### ISSUE TITLE
Comparison between two conditions with multiple biological replicates 

### ISSUE THREAD

**Issue by dg520** [loosolab/TOBIAS#68]
Hi,

Thanks for developing and maintaining this great tool for TF footprint calling and visualization. 
I have a technical question after reading the manual. Is it possible to identify differentially bound motifs between two conditions, where each condition contains multiple biological replicates?
If so, how to implement it via TOBIAS?
If not, do you recommend to merge biological replicates before calling `BINDetect`? What is the best practice to merge multiple bigwig files (sum. average or max)? 

Really appreciate your help.

Best,
Dadi

**Comment by msbentsen** [comment]
Hi Dadi,

Thanks for reaching out. It is not possible to give the replicates directly to TOBIAS, but I would suggest that you pool the reads from the replicates prior to running any of the TOBIAS tools. E.g.:

- Merge replicates into condition1.bam and condition2.bam
- Establish a peak set (the merged peak set of both conditions)
- Run ATACorrect and ScoreBigwig for each condition
- Lastly run BINDetect with the footprint input per condition

Issue https://github.com/loosolab/TOBIAS/issues/7 also gives the same idea. If you are using the TOBIAS snakemake pipeline (https://github.molgen.mpg.de/loosolab/TOBIAS_snakemake), these steps are all done automatically!

Hope this answered your question.

Best, Mette

**Comment by dg520** [comment]
@msbentsen Thanks a lot for your advice! May I also have some following questions please:
1. Is it mandatory that the chromosome names must start with "chr", as I saw in the instruction of `test_data` generation that "chr" was added to an Ensembl GTF? All my alignments and upstream analyses have been done against unmodified Ensembl annotation, where no "chr" has been used. Do I have to add "chr" in the input bam as well?

2. To merge replicates, do I merge the original alignments or do I merge de-duplicated BAM files? The latter seems to make sense for me, as that is used for peak calling (i.e. MACS2) as well. But I'm not sure if it's the same for TOBIAS.

Thanks again in advance!

**Comment by msbentsen** [comment]
>     1. Is it mandatory that the chromosome names must start with "chr"
No, this is not mandatory, as long as all files used (e.g. .bed/.bam) apply the same naming.

>     2. To merge replicates, do I merge the original alignments or do I merge de-duplicated BAM files? 
Good question, but yes, you are right, I would also merge after de-duplication! As the PCR-duplicates etc. should only be handled within each replicate as to not mess with the quantification of unique Tn5 cuts.

**Comment by dg520** [comment]
@msbentsen Hi Mett,

It has run all good according to your suggestions. The only problem I encounter now is the random failure during `TOBIAS BINDetect`. Some jobs have completed successfully but the other ones failed with the following error message:

```
2021-05-02 10:49:08 (58139) [ERROR]     Multiprocessing logger lost connection to queue - probably due to an error raised from a child process.

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/multiprocessing/pool.py", line 121, in worker
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/tobias/tools/bindetect_functions.py", line 565, in process_tfbs
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py", line 2678, in savefig
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/matplotlib/figure.py", line 2962, in savefig
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2230, in print_figure
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/matplotlib/figure.py", line 2738, in draw
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/matplotlib/_api/deprecation.py", line 431, in wrapper
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2885, in draw
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2826, in _update_title_position
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/matplotlib/text.py", line 903, in get_window_extent
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/matplotlib/text.py", line 308, in _get_layout
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/matplotlib/backends/_backend_pdf_ps.py", line 109, in get_text_width_height_descent
RuntimeError: In set_text: Could not load glyph (error code 0x55)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/PHShome/dg520/anaconda3/envs/chipseq/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.12.10', 'console_scripts', 'TOBIAS')())
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 615, in run_bindetect
    results = [task.get() for task in task_list]
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 615, in <listcomp>
    results = [task.get() for task in task_list]
  File "/PHShome/dg520/anaconda3/envs/chipseq/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
RuntimeError: In set_text: Could not load glyph (error code 0x55)
```

I run each of those jobs with 8 cores. Is there anything I should look into to mitigate the error? Thanks!

**Comment by msbentsen** [comment]
Hi @dg520, thank you for your investigations! I never had this issue before, so I don't immediately know how to solve it.

I noticed that [this answer](https://github.com/matplotlib/matplotlib/issues/13723#issuecomment-784612935) mentions downgrading to matplotlib 3.2.1 solves the problem. As far as I can see, TOBIAS is only pinned to 'matplotlib>=2', but there might be some other dependencies requiring matplotlib higher than that. Can you confirm if it is possible to downgrade to 3.2.1? Or if not, which packages prohibit it?

**Comment by dg520** [comment]
@msbentsen Hi Mett, My conda environment only contains Tobias and its dependencies, installed from bioconda channel. It prevents me from downgrading matplotlib to 3.2.1 because:
```
conda install matplotlib=3.2.1

Encountered problems while solving:
  - package qt-5.12.9-hda022c4_4 requires icu >=68.1,<69.0a0, but none of the providers can be installed
```

The `qt-5.12.9` is mandate because the requirement for `pyqtwebengine`. There is only one version of `pyqtwebengine` in the conda channel. 

I understand `pip install` might be a better option to avoid this complex chain dependencies. I just tried to avoid using it to keep the compatibilities between packages.

I really appreciate your help, Mett. I guess I will just live with it at the moment.
