### ISSUE TITLE
error using meme format motifs

### ISSUE THREAD

**Issue by StevenVB12** [loosolab/TOBIAS#77]
Dear Mette Bentson,

When running BINdetect I get the belowissue with my motifs. I'm including an example of my MEME file. Any idea what may be causing this?

Many thanks for any help!

Steven

````
# TOBIAS 0.12.10 BINDetect (run started 2021-06-16 17:04:57.407317)
# Working directory: /work/rpapa/share/TOBIAS
# Command line call: TOBIAS BINDetect --motifs /work/rpapa/share/TOBIAS/motifs_meme/motif_1.txt --signals /work/rpapa/share/TOBIAS/erato.TExATAcxunique100_footprints.bw --genome /work/rpapa/share/REF/H_erato_dem/Herato_final.fasta --peaks /work/rpapa/share/TOBIAS/erato.TExATAcxunique100_peaks_start_end_original.rowsort.scafpos.bed --outdir BINDetect --cond_names erato_TE --cores 8

# ----- Input parameters -----
# signals:      ['/work/rpapa/share/TOBIAS/erato.TExATAcxunique100_footprints.bw']
# peaks:        /work/rpapa/share/TOBIAS/erato.TExATAcxunique100_peaks_start_end_original.rowsort.scafpos.bed
# motifs:       ['/work/rpapa/share/TOBIAS/motifs_meme/motif_1.txt']
# genome:       /work/rpapa/share/REF/H_erato_dem/Herato_final.fasta
# cond_names:   ['erato_TE']
# peak_header:  None
# naming:       name_id
# motif_pvalue: 0.0001
# bound_pvalue: 0.001
# pseudo:       None
# time_series:  False
# skip_excel:   False
# output_peaks: None
# prefix:       bindetect
# outdir:       /work/rpapa/share/TOBIAS/BINDetect
# cores:        8
# split:        100
# verbosity:    3


# ----- Output files -----
# /work/rpapa/share/TOBIAS/BINDetect/*/beds/*_erato_TE_bound.bed
# /work/rpapa/share/TOBIAS/BINDetect/*/beds/*_erato_TE_unbound.bed
# /work/rpapa/share/TOBIAS/BINDetect/*/beds/*_all.bed
# /work/rpapa/share/TOBIAS/BINDetect/*/plots/*_log2fcs.pdf
# /work/rpapa/share/TOBIAS/BINDetect/*/*_overview.txt
# /work/rpapa/share/TOBIAS/BINDetect/*/*_overview.xlsx
# /work/rpapa/share/TOBIAS/BINDetect/bindetect_distances.txt
# /work/rpapa/share/TOBIAS/BINDetect/bindetect_results.txt
# /work/rpapa/share/TOBIAS/BINDetect/bindetect_results.xlsx
# /work/rpapa/share/TOBIAS/BINDetect/bindetect_figures.pdf


2021-06-16 17:04:57 (18617) [INFO]      ----- Processing input data -----
2021-06-16 17:04:57 (18617) [INFO]      Checking reading/writing of files
2021-06-16 17:04:57 (18617) [INFO]      Reading peaks
2021-06-16 17:04:57 (18617) [INFO]      - Found 678 regions in input peaks
2021-06-16 17:04:57 (18617) [INFO]      - Merged to 677 regions
2021-06-16 17:04:57 (18617) [INFO]      Checking for match between --peaks and --fasta/--signals boundaries
2021-06-16 17:04:57 (18617) [INFO]      - Comparing peaks to /work/rpapa/share/REF/H_erato_dem/Herato_final.fasta
2021-06-16 17:04:57 (18617) [INFO]      - Comparing peaks to /work/rpapa/share/TOBIAS/erato.TExATAcxunique100_footprints.bw
2021-06-16 17:04:57 (18617) [INFO]      Estimating GC content from peak sequences
2021-06-16 17:04:57 (18617) [INFO]      - GC content estimated at 40.76%
2021-06-16 17:04:57 (18617) [INFO]      Reading motifs from file
Traceback (most recent call last):
  File "/cm/shared/apps/python3/3.6.10/bin/TOBIAS", line 11, in <module>
    load_entry_point('tobias==0.12.10', 'console_scripts', 'TOBIAS')()
  File "/cm/shared/apps/python3/3.6.10/lib/python3.6/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)
  File "/cm/shared/apps/python3/3.6.10/lib/python3.6/site-packages/tobias/tools/bindetect.py", line 223, in run_bindetect
    motif_list += MotifList().from_file(f)  #List of OneMotif objects
  File "/cm/shared/apps/python3/3.6.10/lib/python3.6/site-packages/tobias/utils/motifs.py", line 253, in from_file
    for c in range(motif.length):
TypeError: 'NoneType' object cannot be interpreted as an integer
````

MEME file:

````
MEME version 4

ALPHABET= ACGT

strands: + -

Background letter frequencies (from file `TExATAcaround_meme/dem_hydara_peaks_Genrich_all_merged.m1.mod'):
A 0.31000 C 0.19000 G 0.19000 T 0.31000 

MOTIF 1 CAGMGNGA-DREME-1

letter-probability matrix: alength= 4 w= 8 nsites= 10974 E= 1.4e-1262
  0.000000	  1.000000	  0.000000	  0.000000	
  1.000000	  0.000000	  0.000000	  0.000000	
  0.000000	  0.000000	  1.000000	  0.000000	
  0.652542	  0.347458	  0.000000	  0.000000	
  0.000000	  0.000000	  1.000000	  0.000000	
  0.098779	  0.266721	  0.303900	  0.330600	
  0.000000	  0.000000	  1.000000	  0.000000	
  1.000000	  0.000000	  0.000000	  0.000000	

MOTIF 2 CTYAACRC-DREME-2

letter-probability matrix: alength= 4 w= 8 nsites= 10470 E= 1.0e-1159
  0.000000	  1.000000	  0.000000	  0.000000	
  0.000000	  0.000000	  0.000000	  1.000000	
  0.000000	  0.584241	  0.000000	  0.415759	
  1.000000	  0.000000	  0.000000	  0.000000	
  1.000000	  0.000000	  0.000000	  0.000000	
  0.000000	  1.000000	  0.000000	  0.000000	
  0.661891	  0.000000	  0.338109	  0.000000	
  0.000000	  1.000000	  0.000000	  0.000000	
````

**Comment by msbentsen** [comment]
Hi Steven,

Thank you for your issue. I don't get any error with the two motifs you just posted (but I assume the file is longer than that).

I found that TOBIAS might complain if there are 'MOTIF' lines without matrices, e.g.:
```
MEME version 4

ALPHABET= ACGT

strands: + -

Background letter frequencies (from file `TExATAcaround_meme/dem_hydara_peaks_Genrich_all_merged.m1.mod'):
A 0.31000 C 0.19000 G 0.19000 T 0.31000 

MOTIF 1 CAGMGNGA-DREME-1

letter-probability matrix: alength= 4 w= 8 nsites= 10974 E= 1.4e-1262
  0.000000	  1.000000	  0.000000	  0.000000	
  1.000000	  0.000000	  0.000000	  0.000000	
  0.000000	  0.000000	  1.000000	  0.000000	
  0.652542	  0.347458	  0.000000	  0.000000	
  0.000000	  0.000000	  1.000000	  0.000000	
  0.098779	  0.266721	  0.303900	  0.330600	
  0.000000	  0.000000	  1.000000	  0.000000	
  1.000000	  0.000000	  0.000000	  0.000000	

MOTIF 2 CAGMGNGA-DREME-1

MOTIF 3 CAGMGNGA-DREME-1

MOTIF 4 CTYAACRC-DREME-2

letter-probability matrix: alength= 4 w= 8 nsites= 10470 E= 1.0e-1159
  0.000000	  1.000000	  0.000000	  0.000000	
  0.000000	  0.000000	  0.000000	  1.000000	
  0.000000	  0.584241	  0.000000	  0.415759	
  1.000000	  0.000000	  0.000000	  0.000000	
  1.000000	  0.000000	  0.000000	  0.000000	
  0.000000	  1.000000	  0.000000	  0.000000	
  0.661891	  0.000000	  0.338109	  0.000000	
  0.000000	  1.000000	  0.000000	  0.000000	
```
Can you check whether this is the case in your file? I will also work on a better error message. Thanks!

Best Mette

**Comment by StevenVB12** [comment]
Dear Mette,

Thank you for your quick response. I just copied the first part of your MEME example and still get the same error.

````

MEME version 4



ALPHABET= ACGT



strands: + -



Background letter frequencies (from file `TExATAcaround_meme/dem_hydara_peaks_Genrich_all_merged.m1.mod'):

A 0.31000 C 0.19000 G 0.19000 T 0.31000



MOTIF 1 CAGMGNGA-DREME-1



letter-probability matrix: alength= 4 w= 8 nsites= 10974 E= 1.4e-1262

  0.000000       1.000000       0.000000       0.000000

  1.000000       0.000000       0.000000       0.000000

  0.000000       0.000000       1.000000       0.000000

  0.652542       0.347458       0.000000       0.000000

  0.000000       0.000000       1.000000       0.000000

  0.098779       0.266721       0.303900       0.330600

  0.000000       0.000000       1.000000       0.000000

  1.000000       0.000000       0.000000       0.000000
````

Would be interesting to know if this exact one works for you.

Many thanks,

Steven

**Comment by msbentsen** [comment]
Hi again Steven,

Good news - I found the bug, and have fixed this in `tobias 0.12.11`. Please fetch this version from PyPI (or from bioconda as soon as the repository updates). I hope this fixues the issue, and otherwise, feel free to let me know. Thanks!

Best Mette

**Comment by StevenVB12** [comment]
Works!

Huge thanks,

Steven

**Comment by StevenVB12** [comment]
Dear Mette,

now that I'm getting results, may I ask you what you think could cause a pattern like this:

![image](https://user-images.githubusercontent.com/6349171/123463079-169d3680-d5b9-11eb-9edd-fb9f962c63b6.png)

Or what I might be doing wrong...

Many thanks in any case!

Steven

**Comment by msbentsen** [comment]
Hi Steven,

Hard to say - there are some TFs which do not seem to create footprints, and like you see here, even seem to cause more insertions! So far, this seems to be related to both the type of TF, the binding dynamics, biological condition and data quality, so it is hard to give a definitive answer. Depending on the motifs you are using, you might have a look at a TF like "CTCF", which always creates a strong footprint. If you see a good footprint, you can conclude that the quality of the data is good, but that this specific TF (`STREME-1_1-CCG(...)`) does not produce clear footprints. If CTCF does not produce a footprint, you might have a look at whether the bias correction, footprinting etc. worked as intended.

In the end, all TFs not producing footprints will be scored on the accessibility, so you can still interpret the output footprint scores as more/less (chance of) binding. 

Best Mette

**Comment by StevenVB12** [comment]
Dear Mette,

thank you for you response. I tried CTF like you suggested (note I'm working with butterfly ATAC data and used here the human motif for CTCF). I get a very similar result as with the previously tested motif:

![image](https://user-images.githubusercontent.com/6349171/123672975-ebf7eb80-d80d-11eb-9435-d8bc1cf5242f.png)

Sorry to keep asking your time on this, but it looks like there's strong patterns, just opposite of what i expected.

Many thanks,

Steven

**Comment by msbentsen** [comment]
Hi Steven,

Uh I am not familiar with the results from butterfly ATAC - I am not sure if CTCF is conserved in function? 

I can only encourage you to check the general ATAC-seq quality measures like insertion-size distribution plots, reads-in-peaks enrichment (=signal-to-noise ratio) and mapping rate etc. If these look good, you can make better assumptions about why some TFs might not be creating strong footprints. Otherwise, as I mentioned, you can still use the footprinting values, although these will be mostly driven by accessibility.

Best Mette
