### ISSUE TITLE
Error in ATACorrect

### ISSUE THREAD

**Issue by celinajose** [loosolab/TOBIAS#90]
Hey!

I got the following error while running the ATACorrect:

```Traceback (most recent call last):
  File "/home/cjose/Software/anaconda3/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.12.12', 'console_scripts', 'TOBIAS')())
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/tobias-0.12.12-py3.8-linux-x86_64.egg/tobias/TOBIAS.py", line 149, in main
    module = importlib.import_module(mod_name)	#load specific module
  File "/home/cjose/Software/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/tobias-0.12.12-py3.8-linux-x86_64.egg/tobias/tools/atacorrect.py", line 40, in <module>
    from tobias.tools.atacorrect_functions import *
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/tobias-0.12.12-py3.8-linux-x86_64.egg/tobias/tools/atacorrect_functions.py", line 33, in <module>
    from tobias.utils.regions import OneRegion, RegionList
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/tobias-0.12.12-py3.8-linux-x86_64.egg/tobias/utils/regions.py", line 24, in <module>
    import sklearn.preprocessing as preprocessing
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/sklearn/base.py", line 13, in <module>
    from .utils.fixes import signature
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 14, in <module>
    from . import _joblib
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/sklearn/utils/_joblib.py", line 22, in <module>
    from ..externals import joblib
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/loky/__init__.py", line 12, in <module>
    from .backend.reduction import set_loky_pickler
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/loky/backend/reduction.py", line 125, in <module>
    from sklearn.externals.joblib.externals import cloudpickle  # noqa: F401
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 167, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/cjose/Software/anaconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 148, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)
```

Can you try to help me solve this issue?

Thanks in advance,

**Comment by msbentsen** [comment]
Hi @celinajose,

This looks more like an installation/package problem rather than a direct error with TOBIAS. It seems to be triggered by an error in .cloudpickle, which is needed by the sklearn.preprocessing module. Can you share an overview of the version information for your current python installation? Either `pip freeze` or `conda list` should do the job.

I saw this issue (https://github.com/cloudpipe/cloudpickle/issues/404) from Cloudpickle saying that downgrading to python 3.7 fixes the issue, so maybe you can also try that. Let me know if that solves the issue!

BR Mette
