### ISSUE TITLE
BINDetect import error

### ISSUE THREAD

**Issue by anacatalan** [loosolab/TOBIAS#93]
Dear Mette,

I have run into an error while running BINDetect:

bwt=/dss/dsslegfs01/pr53da/pr53da-dss-0018/projects/2017__DosageCompensation/atacSeq2/TOBIAS/finished_run/0.34_QC20_PP_D_Ko_C59_female_Spleen_chr1/0.34_QC20_PP_D_Ko_C59_female_Spleen_chr1_corrected.bw
genome=/dss/dsslegfs01/pr53da/pr53da-dss-0018/assemblies/Corvus.cornix/genome/v5/v5.7/Corvus_cornix__S_Up_H32__v5.7.fasta
bed=/dss/dsslegfs01/pr53da/pr53da-dss-0018/projects/2017__DosageCompensation/atacSeq2/MACS/narrowPeak_files/0.34_QC20_PP_D_Ko_C59_female_Spleen_chr1_peaks.narrowPeak
data_base=/dss/dsslegfs01/pr53da/pr53da-dss-0018/projects/2017__DosageCompensation/atacSeq2/TOBIAS/meme_databases/motif_databases/CIS-BP_2.00/Taeniopygia_guttata.meme

TOBIAS BINDetect --motifs $data_base --signals $bwt --genome $genome --peaks $bed --outdir BINDetect_test --cores 8
Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "/dss/dsshome1/lxc07/lu32gib/miniconda3/envs/TOBIAS_ENV/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.12.11', 'console_scripts', 'TOBIAS')())
  File "/dss/dsshome1/lxc07/lu32gib/miniconda3/envs/TOBIAS_ENV/lib/python3.7/site-packages/tobias-0.12.11-py3.7-linux-x86_64.egg/tobias/TOBIAS.py", line 149, in main
    module = importlib.import_module(mod_name)	#load specific module
  File "/dss/dsshome1/lxc07/lu32gib/miniconda3/envs/TOBIAS_ENV/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/dss/dsshome1/lxc07/lu32gib/miniconda3/envs/TOBIAS_ENV/lib/python3.7/site-packages/tobias-0.12.11-py3.7-linux-x86_64.egg/tobias/tools/bindetect.py", line 43, in <module>
    from tobias.tools.bindetect_functions import *
  File "/dss/dsshome1/lxc07/lu32gib/miniconda3/envs/TOBIAS_ENV/lib/python3.7/site-packages/tobias-0.12.11-py3.7-linux-x86_64.egg/tobias/tools/bindetect_functions.py", line 48, in <module>
    from tobias.utils.signals import *
ImportError: /dss/dsshome1/lxc07/lu32gib/miniconda3/envs/TOBIAS_ENV/lib/python3.7/site-packages/tobias-0.12.11-py3.7-linux-x86_64.egg/tobias/utils/signals.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _intel_fast_memcmp

Do you know what might be causing this error?

Thanks and best!

Ana

**Comment by msbentsen** [comment]
Hi @anacatalan,
Did you solve this issue?

**Comment by anacatalan** [comment]
Hi Mette,

I manage to run FootprintScores and BINDetect using TOBIAS 0.8.0. I also
installed TOBIAS 0.12.11 at our server but then I got this message:

TOBIAS ScoreBigwig --signal $bwt --regions $bed --output testing --cores 8

Traceback (most recent call last):

  File "/dss/dsshome1/lxc07/lu32gib/miniconda3/envs/TOBIAS_ENV/bin/TOBIAS",
line 33, in <module>

    sys.exit(load_entry_point('tobias==0.12.11', 'console_scripts',
'TOBIAS')())

  File
"/dss/dsshome1/lxc07/lu32gib/miniconda3/envs/TOBIAS_ENV/lib/python3.7/site-packages/tobias-0.12.11-py3.7-linux-x86_64.egg/tobias/TOBIAS.py",
line 149, in main

    module = importlib.import_module(mod_name) #load specific module

  File
"/dss/dsshome1/lxc07/lu32gib/miniconda3/envs/TOBIAS_ENV/lib/python3.7/importlib/__init__.py",
line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in
_call_with_frames_removed

  File
"/dss/dsshome1/lxc07/lu32gib/miniconda3/envs/TOBIAS_ENV/lib/python3.7/site-packages/tobias-0.12.11-py3.7-linux-x86_64.egg/tobias/tools/score_bigwig.py",
line 28, in <module>

    from tobias.utils.sequences import *
ImportError:
/dss/dsshome1/lxc07/lu32gib/miniconda3/envs/TOBIAS_ENV/lib/python3.7/site-packages/tobias-0.12.11-py3.7-linux-x86_64.egg/tobias/utils/
sequences.cpython-37m-x86_64-linux-gnu.so: undefined symbol:
_intel_fast_memcmp

Sorry I deleted the first entry of this thread since I noticed that I ran
TOBIAS using the wrong input file.

Cheers and many thanks for your time!

Ana

Ana Catalán, PhD
Postdoctoral Fellow
Division of Evolutionary Biology
Faculty of Biology
Ludwig-Maximilians-Universität München
Grosshaderner Strasse 2
82152 Planegg-Martinsried
Germany

**Comment by msbentsen** [comment]
Hi Ana,

Just to confirm: it works for you locally, but on the server, it throws the error above?

It looks like it is rather an issue of setup on that specific system. I googled "undefined symbol: _intel_fast_memcmp" and got to this issue of another repository: https://github.com/Unidata/netcdf4-python/issues/643#issuecomment-293477379

Maybe you can have a look and see if you can re-install TOBIAS using the code from github + the `CC=gcc` commands mentioned in the comment. So within the conda environment:
```
git clone https://github.com/loosolab/TOBIAS.git
cd TOBIAS
CC=gcc python setup.py build
CC=gcc python setup.py install
```

Let me know how it works out!

Best Mette

**Comment by anacatalan** [comment]
Hi Mette,

I installed version 0.8.0 (using conda) and 0.12.11 (as indicated in the
manual) at our hpc and  0.12.11 was giving me the "undefined symbol:
_intel_fast_memcmp" error. I will install TOBIAS again as you are
recommending. I have one question, would the *_corrected.bw produced
by FootprintScores 0.8.0 be compatible with BINDetect 0.12.11?

Thanks and cheers,

Ana

Ana Catalán, PhD
Postdoctoral Fellow
Division of Evolutionary Biology
Faculty of Biology
Ludwig-Maximilians-Universität München
Grosshaderner Strasse 2
82152 Planegg-Martinsried
Germany

**Comment by msbentsen** [comment]
Great, I hope the new installation helps.

And yes, the bigwigs will be compatible - however, there were quite a lot of smaller changes and bugfixes since 0.8.0, so I would probably recommend you to recalculate it with the newer version anyway. Just to make sure that the scores are correct.
