### ISSUE TITLE
Issues with MACS environment in TOBIAS snakemake 

### ISSUE THREAD

**Issue by ccasar** [loosolab/TOBIAS#95]
Hi,

not sure if this is the right place to post issues with the [snakemake workflow](https://github.molgen.mpg.de/loosolab/TOBIAS_snakemake).

I have run into multiple issues with the following command run from within the tobias_snakemake_env:
```
for co in `ls configs/*yaml`; do snakemake --conda-prefix /home/ccasar/miniconda3/envs --use-conda --conda-frontend mamba   --configfile $co  --cores 10 ;done
```
* I'm using `--conda-prefix` because without it, setting up the other environments fails with `PaddingError: Placeholder of length '80' too short in package`. 
* I'm using `--conda-frontend mamba` because with conda even after ~16 hours of waiting the MACS environment was still in the `Downloading and installing remote packages.` phase. 

Using mamba snakemake was able to setup the MACS environment  but immediately failed with the following error:
```
Traceback (most recent call last):
  File "/home/ccasar/miniconda3/envs/8d8ba86bff328a1f03a4371b9f642b08/bin/macs2", line 650, in <module>
    main()
  File "/home/ccasar/miniconda3/envs/8d8ba86bff328a1f03a4371b9f642b08/bin/macs2", line 48, in main
    from MACS2.callpeak_cmd import run
  File "/home/ccasar/miniconda3/envs/8d8ba86bff328a1f03a4371b9f642b08/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 23, in <module>
    from MACS2.OptValidator import opt_validate
  File "/home/ccasar/miniconda3/envs/8d8ba86bff328a1f03a4371b9f642b08/lib/python2.7/site-packages/MACS2/OptValidator.py", line 20, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 918, in init MACS2.IO.Parser
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

Adding `defaults` to the channel list before conda-forge in macs.yaml speeds up the setup process with conda instead of mamba significantly but results in the same numpy error above. 
All these steps were run with the most recent version of the repo pulled yesterday.

I was able to successfully run this workflow in December 2020 using conda to setup everything 

Do you have any idea how to solve this?

**Comment by ccasar** [comment]
Changing python=2 requirement to just python seems to do the trick.

In the [nextflow version](https://github.molgen.mpg.de/loosolab/TOBIAS-nextflow/blob/4161ef280ee25ee67ad66b1680695c14dff6d16c/TOBIAS_MAPOKS/environments/macs.yaml) of the MACS environment there is also no requirement for pyhton2.

Is there  a reason to specifically require python2 with snakemake?

**Comment by ccasar** [comment]
Yes, removing the pyhthon2 requirement seemed to resolve the issue.Thanks!
